<?php
$title = 'Agregar medicamento';
$this->headTitle($title);
?>

<h3><?php echo $this->escapeHtml($title); ?></h3><?php

if (isset($Success) and $Success): ?>
<div class="alert alert-success alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong>  El medicamento ha sido registrado satisfactoriamente
</div>
	<?php if (!$xmlHttpRequest): ?>
		<a href="<?php echo $this->url('settings', array('action'=>'index')); ?>" class="btn btn-default">Regresar</a>
	<?php endif; ?>
<?php endif;

if (isset($Exception)): ?>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> <?= $Exception ?>
</div>
<?php endif;

if (isset($form)):
	$form->setAttribute('action', $this->url('settings', array('action' => 'add-medication')));
	$form->prepare();
	echo $this->form()->openTag($form);
	echo $this->formRow($form->get('nom_med'));
	echo $this->formRow($form->get('nom_gen'));
	echo $this->formRow($form->get('con_med'));
	echo $this->formRow($form->get('pre_med'));
	echo $this->formRow($form->get('est_med'));
	if (!$xmlHttpRequest):
		echo $this->formSubmit($form->get('submit'));
	endif;
	echo $this->form()->closeTag();
endif;
