<?php if (isset($Exception)): ?>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> <?= $Exception ?>
</div>
<?php endif; ?>

<?php if (!isset($Exception)): ?>
	<?php
	$title = 'Eliminar medicamento';
	$this->headTitle($title);
	?>
	<h3><?php echo $this->escapeHtml($title); ?></h3>

	<p>Estás seguro de que deseas eliminar el medicamento
		<strong><?php echo $this->escapeHtml($medication->nom_med); ?></strong> con id
		<strong><?php echo $this->escapeHtml($medication->cod_med); ?></strong> ?
	</p>
	<?php
		$url = $this->url('settings', array(
			'action' => 'delete-medications',
			'id'     => $this->id,
		));
	?>
	<form action="<?php echo $url; ?>" method="post">
		<div>
			<input type="hidden" name="id" value="<?php echo (int) $medication->cod_med; ?>" />
			<input type="submit" name="del" value="Si" class="btn btn-danger" />
			<input type="submit" name="del" value="No" class="btn btn-primary" />
		</div>
	</form>
<?php endif; ?>