<?php if (isset($Exception)): ?>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> <?= $Exception ?>
</div>
<?php endif; ?>

<?php if (!isset($Exception)): ?>	
	<?php
	$title = 'Eliminar exámen';
	$this->headTitle($title);
	?>
	<h1><?php echo $this->escapeHtml($title); ?></h1>

	<p>Estás seguro de que deseas eliminar el exámen
		<strong><?php echo $this->escapeHtml($exam->nom_exa); ?></strong> con id
		<strong><?php echo $this->escapeHtml($exam->cod_exa); ?></strong> ?
	</p>
	<?php
		$url = $this->url('settings', array(
			'action' => 'delete-exams',
			'id'     => $this->id,
		));
	?>
	<form action="<?php echo $url; ?>" method="post">
		<div>
			<input type="hidden" name="id" value="<?php echo (string) $exam->cod_exa; ?>" />
			<input type="submit" name="del" value="Si" class="btn btn-danger" />
			<input type="submit" name="del" value="No" class="btn btn-primary" />
		</div>
	</form>
<?php endif; ?>