<?php
$title = 'Editar Exámen';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>

<?php if (isset($Success) and $Success): ?>
<div class="alert alert-success alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong>  El exámen ha sido editado satisfactoriamente
</div>
	<?php if (!$xmlHttpRequest): ?>
		<a href="<?php echo $this->url('settings', array('action'=>'index')) ?>" class="btn btn-primary">Volver</a><br /><br />
	<?php endif; ?>
<?php endif;

if (isset($Exception)): ?>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> <?= $Exception ?>
</div>
<?php endif; ?>

<?php
if (isset($form))
{
	$form = $this->form;
	$form->setAttribute(
		'action', $this->url('settings',
		array(
			'action' => 'edit-exam',
			'id'     => $this->id,
		)
	));
	$form->prepare();	
	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('cod_exa'));
	echo $this->formRow($form->get('nom_exa'));
	echo $this->formRow($form->get('tip_exa'));
	if (!$xmlHttpRequest):
		echo $this->formSubmit($form->get('submit'));
	endif;
	echo $this->form()->closeTag();
}
?>