<?php if (isset($Exception)): ?>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> <?= $Exception ?>
</div>
<?php endif; ?>

<?php if (!$xmlHttpRequest): ?>
	<a href="<?php echo $this->url('settings', array('action'=>'view-exams')) ?>" class="btn btn-primary">Volver</a><br /><br />
<?php endif; ?>