<?php if (isset($Exception)): ?>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> <?= $Exception ?>
</div>
<?php endif; ?>

<?php if (!isset($Exception)): ?>
  <div class="container">
    <div class="row clearfix">
      <div class="col-md-6 column">
        <div class="list-group">
          <?php if (isset($acl) && $acl->isAllowed("viewExams")): ?>
            <a href="<?php echo $this->url('settings', array('action'=>'view-exams')) ?>" class="list-group-item">
              <h4 class="list-group-item-heading">Exámenes</h4>
            <span class="glyphicon glyphicon-file" style="font-size: 30px; color: rgb(0,150,200)"></span>
              <p class="list-group-item-text">Lista los exámenes registrados
                <button title="Vista rápida" class="btn" data-resource="<?php echo $this->url('settings', array('action'=>'view-exams'));?>" id="exams-mode"><span class="glyphicon glyphicon-chevron-down"></span></button>
              </p>
            </a>
          <?php endif; ?>
          <?php if (isset($acl) && $acl->isAllowed("viewMedications")): ?>
            <a href="<?php echo $this->url('settings', array('action'=>'view-medications')) ?>" class="list-group-item">
              <h4 class="list-group-item-heading">Medicamentos</h4>
            <span class="glyphicon glyphicon-briefcase" style="font-size: 30px; color: rgb(0,150,200)"></span>
              <p class="list-group-item-text">Lista los medicamentos registrados
              <button title="Vista rápida" class="btn" data-resource="<?php echo $this->url('settings', array('action'=>'view-medications'));?>" id="medications-mode"><span class="glyphicon glyphicon-chevron-down"></span></button>
              </p>
            </a>
          <?php endif; ?>
          <?php if (isset($acl) && $acl->isAllowed("viewEntities")): ?>
            <a href="<?php echo $this->url('settings', array('action'=>'view-entities')) ?>" class="list-group-item">
              <h4 class="list-group-item-heading">Entidades</h4>
            <span class="glyphicon glyphicon-flag" style="font-size: 30px; color: rgb(0,150,200)"></span>
              <p class="list-group-item-text">Lista las entidades registradas
              <button title="Vista rápida" class="btn" data-resource="<?php echo $this->url('settings', array('action'=>'view-entities'));?>" id="entities-mode"><span class="glyphicon glyphicon-chevron-down"></span></button>
              </p>
            </a>
          <?php endif; ?>
        </div>      
      </div>
      <div class="col-md-6 column">
        <h4>Registro</h4>
        <ul class="list-group">
        <?php if ($num_exams): ?>
          <li class="list-group-item">
            <span class="badge"><?= $num_exams ?></span>
            Exámenes
          </li>
        <?php endif; ?>
        <?php if ($num_medications): ?>
          <li class="list-group-item">
            <span class="badge"><?= $num_medications ?></span>
            Medicamentos
          </li>
        <?php endif; ?>
        <?php if ($num_entities): ?>
          <li class="list-group-item">
            <span class="badge"><?= $num_entities ?></span>
            Entidades
          </li>
        <?php endif; ?>
        </ul>
      </div>
    </div>
  </div>
  <div id="view"></div>
<?php endif; ?>