<?php if (isset($Exception)): ?>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> <?= $Exception ?>
</div>
<?php endif; ?>

<?php if (!isset($Exception)): ?>
  <?php if (!$xmlHttpRequest): ?>
    <span class="glyphicon glyphicon-cog" style="font-size: 20px; color: rgb(0,150,200)"></span>
    <h3 style="display: inline-block">Administrador de medicamentos</h3>
  <?php endif; ?>

  <?php if (!$xmlHttpRequest || !$simulateXmlHttpRequest): ?>
    <div id="setting-controls">
    <p>
        <div class="input-group" style="width: 200px; float: left; margin: 0 5px 0 0;">
            <input type="search" placeholder="búsqueda" class="form-control" id="general-search" 
            data-url="<?php echo $this->url('settings', array('action'=>'view-medications'));?>" autofocus="autofocus" />
            <div class="input-group-btn">
            <button type="button" id="run-general-search" class="btn btn-default" tabindex="-1" style="border-left: none;">
                <span class="glyphicon glyphicon-search">
            </button>
            </div>
        </div>

        <div class="btn-group">
          <?php if (isset($acl) && $acl->isAllowed("addMedications")): ?>
            <button type="button" class="btn btn-default" id="general-add" data-resource="<?php echo $this->url('settings', array('action'=>'add-medication')) ?>"><span class="glyphicon glyphicon-plus"></span></button>
          <?php endif; ?>
          <?php if (isset($acl) && $acl->isAllowed("editMedications")): ?>        
            <button type="button" class="btn btn-default" id="edit-general-selection" data-resource="<?php echo $this->url('settings', array('action'=>'edit-medication')) ?>"><span class="glyphicon glyphicon-pencil"></span></button>
          <?php endif; ?>
          <?php if (isset($acl) && $acl->isAllowed("deleteMedications")): ?>
            <button type="button" class="btn btn-default hidden" id="del-general-selection" data-resource="<?php echo $this->url('settings', array('action'=>'delete-medications')) ?>"><span class="glyphicon glyphicon-trash"></span></button>
          <?php endif; ?>
          <?php if (isset($acl) && $acl->isAllowed("disbleMedications")): ?>
            <button type="button" class="btn btn-default" id="disable-general-selection" data-resource="<?php echo $this->url('settings', array('action'=>'disable-medications')) ?>"><span class="glyphicon glyphicon-ban-circle"></span></button>
          <?php endif; ?>
          <?php if (isset($acl) && $acl->isAllowed("enableMedications")): ?>
            <button type="button" class="btn btn-default" id="enable-general-selection" data-resource="<?php echo $this->url('settings', array('action'=>'enable-medications')) ?>"><span class="glyphicon glyphicon-ok"></span></button>
          <?php endif; ?>
        </div>
    </p>
    </div>
  <?php endif; ?>

  <div id="view-general-search">
    <?php if (count($medications)): ?>
      <table class="table table-striped table-hover">
          <tr>
              <th><input id="app-general-check" type="checkbox" /></th>
              <th>Código</th>
              <th>Medicamento</th>
              <th>Concentración</th>
              <th>Presentación</th>
              <th>Estado</th>
              <th>Acciones</th>
          </tr>
          <?php foreach ($medications as $medication) : ?>
          <tr>
              <td><input type="checkbox" data-selection-id="<?= $medication->cod_med ?>" class="general-input-selection"></td>
              <td><?php echo $this->escapeHtml($medication->cod_med);?></td>
              <td><?php echo $this->escapeHtml($medication->nom_med);?></td>
              <td><?php echo $this->escapeHtml($medication->con_med);?></td>
              <td><?php echo $this->escapeHtml($medication->pre_med);?></td>
              <td><?= ($medication->est_med == 1) ? "Activo": "Inactivo"; ?></td>
          <td>
            <?php if (isset($acl) && $acl->isAllowed("editMedications")): ?>
              <a href="<?php echo $this->url('settings',
              array('action'=>'edit-medication', 'id' => $medication->cod_med));?>"
              class="" title="editar"><span class="glyphicon glyphicon-pencil"></span></a>
            <?php endif; ?>
            <?php if (isset($acl) && $acl->isAllowed("disableMedications")): ?>
              <a href="<?php echo $this->url('settings',
              array('action'=>'disable-medications', 'id' => $medication->cod_med));?>"
              class="" title="deshabilitar"><span class="glyphicon glyphicon-ban-circle"></span></a>
            <?php endif; ?>
            <?php if (isset($acl) && $acl->isAllowed("enableMedications")): ?>
              <a href="<?php echo $this->url('settings',
              array('action'=>'enable-medications', 'id' => $medication->cod_med));?>"
              class="" title="habilitar"><span class="glyphicon glyphicon-ok"></span></a>
            <?php endif; ?>
            <?php if (isset($acl) && $acl->isAllowed("deleteMedications")): ?>
              <a href="<?php echo $this->url('settings',
              array('action'=>'delete-medications', 'id' => $medication->cod_med));?>"
              class="hidden" title="eliminar"><span class="glyphicon glyphicon-trash"></span></a>
            <?php endif; ?>
          </td>
          </tr>
          <?php endforeach; ?>
      </table>
    <?php elseif($empty): ?>
      <div class="panel panel-default">
        <div class="panel-body">
          Aún no se han registrado medicamentos!
        </div>
      </div>
    <?php else: ?>
      <div class="panel panel-default">
        <div class="panel-body">
          No se han encontrado medicamentos que contengan la palabra <strong><?= $this->escapeHtml($needle) ?></strong>
        </div>
      </div>
    <?php endif; ?>
  </div>
<?php endif; ?>