<?php if (isset($Exception)): ?>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> <?= $Exception ?>
</div>
<?php endif; ?>

<?php if (!isset($Exception)): ?>
  <?php if (!$xmlHttpRequest): ?>
    <span class="glyphicon glyphicon-cog" style="font-size: 20px; color: rgb(0,150,200)"></span>
    <h3 style="display: inline-block">Administrador de entidades</h3>
  <?php endif; ?>

  <?php if (!$xmlHttpRequest || !$simulateXmlHttpRequest): ?>
    <div id="setting-controls">
    <p>
        <div class="input-group" style="width: 200px; float: left; margin: 0 5px 0 0;">
            <input type="search" placeholder="búsqueda" class="form-control" id="general-search" 
            data-url="<?php echo $this->url('settings', array('action'=>'view-entities'));?>" autofocus="autofocus" />
            <div class="input-group-btn">
            <button type="button" id="run-general-search" class="btn btn-default" tabindex="-1" style="border-left: none;">
                <span class="glyphicon glyphicon-search"></span>
            </button>
            </div>
        </div>

        <div class="btn-group">
          <?php if (isset($acl) && $acl->isAllowed("addEntities")): ?>
            <button type="button" class="btn btn-default" id="general-add" data-resource="<?php echo $this->url('settings', array('action'=>'add-entity')) ?>"><span class="glyphicon glyphicon-plus"></span></button>
          <?php endif; ?>
          <?php if (isset($acl) && $acl->isAllowed("editEntities")): ?>
            <button type="button" class="btn btn-default" id="edit-general-selection" data-resource="<?php echo $this->url('settings', array('action'=>'edit-entity')) ?>"><span class="glyphicon glyphicon-pencil"></span></button>
          <?php endif; ?>
          <?php if (isset($acl) && $acl->isAllowed("deleteEntities")): ?>
            <button type="button" class="btn btn-default hidden" id="del-general-selection" data-resource="<?php echo $this->url('settings', array('action'=>'delete-entities')) ?>"><span class="glyphicon glyphicon-trash"></span></button>
          <?php endif; ?>
          <?php if (isset($acl) && $acl->isAllowed("disableEntities")): ?>
            <button type="button" class="btn btn-default" id="disable-general-selection" data-resource="<?php echo $this->url('settings', array('action'=>'disable-entities')) ?>"><span class="glyphicon glyphicon-ban-circle"></span></button>
          <?php endif; ?>
          <?php if (isset($acl) && $acl->isAllowed("enableEntities")): ?>
            <button type="button" class="btn btn-default" id="enable-general-selection" data-resource="<?php echo $this->url('settings', array('action'=>'enable-entities')) ?>"><span class="glyphicon glyphicon-ok"></span></button>
          <?php endif; ?>
        </div>
    </p>
    </div>
  <?php endif; ?>

  <div id="view-general-search">
    <?php if (count($entities)): ?>
      <table class="table table-striped table-hover">
          <tr>
              <th><input id="app-general-check" type="checkbox" /></th>
              <th>Código</th>
              <th>Nombre de la entidad</th>
              <th>Dirección</th>
              <th>Estado</th>
              <th>Acciones</th>
          </tr>
          <?php foreach ($entities as $entity) : ?>
          <tr>
              <td><input type="checkbox" data-selection-id="<?= $entity->cod_ent ?>" class="general-input-selection"></td>
              <td><?php echo $this->escapeHtml($entity->cod_ent);?></td>
              <td><?php echo $this->escapeHtml($entity->nom_ent);?></td>
              <td><?= ($this->escapeHtml($entity->dir_ent) != "") ? $this->escapeHtml($entity->dir_ent) : " - "; ?></td>
              <td><?= ($entity->est_ent == 1) ? "Activo": "Inactivo"; ?></td>
          <td>
            <?php if (isset($acl) && $acl->isAllowed("editEntities")): ?>
              <a href="<?php echo $this->url('settings',
              array('action'=>'edit-entity', 'id' => $entity->cod_ent));?>"
              class="" title="editar"><span class="glyphicon glyphicon-pencil"></span></a>
            <?php endif; ?>
            <?php if (isset($acl) && $acl->isAllowed("disableEntities")): ?>
              <a href="<?php echo $this->url('settings',
              array('action'=>'disable-entities', 'id' => $entity->cod_ent));?>"
              class="" title="deshabilitar"><span class="glyphicon glyphicon-ban-circle"></span></a>
            <?php endif; ?>
            <?php if (isset($acl) && $acl->isAllowed("enableEntities")): ?>
              <a href="<?php echo $this->url('settings',
              array('action'=>'enable-entities', 'id' => $entity->cod_ent));?>"
              class="" title="habilitar"><span class="glyphicon glyphicon-ok"></span></a>
            <?php endif; ?>
            <?php if (isset($acl) && $acl->isAllowed("deleteEntities")): ?>
              <a href="<?php echo $this->url('settings',
              array('action'=>'delete-entities', 'id' => $entity->cod_ent));?>"
              class="hidden" title="eliminar"><span class="glyphicon glyphicon-trash"></span></a>
            <?php endif; ?>
          </td>
          </tr>
          <?php endforeach; ?>
      </table>
    <?php elseif($empty): ?>
      <div class="panel panel-default">
        <div class="panel-body">
          Aún no se han registrado entidades!
        </div>
      </div>
    <?php else: ?>
      <div class="panel panel-warning">
        <div class="panel-body">
          No se han encontrado entidades que contengan la palabra <strong><?= $this->escapeHtml($needle) ?></strong>
        </div>
      </div>
    <?php endif; ?>
  </div>
<?php endif; ?>