<?php if (isset($Exception)): ?>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> <?= $Exception ?>
</div>
<?php endif; ?>

<?php if (!isset($Exception)): ?>
  <?php if (!$xmlHttpRequest): ?>
    <span class="glyphicon glyphicon-cog" style="font-size: 20px; color: rgb(0,150,200)"></span>
    <h3 style="display: inline-block">Administrador de exámenes</h3>
  <?php endif; ?>

  <?php if (!$xmlHttpRequest || !$simulateXmlHttpRequest): ?>
    <div id="setting-controls">
    <p>
        <div class="input-group" style="width: 200px; float: left; margin: 0 5px 0 0;">
            <input type="search" placeholder="búsqueda" class="form-control" id="general-search" 
            data-url="<?php echo $this->url('settings', array('action'=>'view-exams'));?>" autofocus="autofocus" />
            <div class="input-group-btn">
            <button type="button" id="run-general-search" class="btn btn-default" tabindex="-1" style="border-left: none;">
                <span class="glyphicon glyphicon-search">
            </button>
            </div>
        </div>

        <div class="btn-group">
          <?php if (isset($acl) && $acl->isAllowed("addExams")): ?>
            <button type="button" class="btn btn-default" id="general-add" data-resource="<?php echo $this->url('settings', array('action'=>'add-exam')) ?>"><span class="glyphicon glyphicon-plus"></span></button>
          <?php endif; ?>
          <?php if (isset($acl) && $acl->isAllowed("editExams")): ?>
            <button type="button" class="btn btn-default" id="edit-general-selection" data-resource="<?php echo $this->url('settings', array('action'=>'edit-exam')) ?>"><span class="glyphicon glyphicon-pencil"></span></button>
          <?php endif; ?>
          <?php if (isset($acl) && $acl->isAllowed("deleteExams")): ?>
            <button type="button" class="btn btn-default hidden" id="del-general-selection" data-resource="<?php echo $this->url('settings', array('action'=>'delete-exams')) ?>"><span class="glyphicon glyphicon-trash"></span></button>
          <?php endif; ?>
          <?php if (isset($acl) && $acl->isAllowed("disableExams")): ?>
            <button type="button" class="btn btn-default" id="disable-general-selection" data-resource="<?php echo $this->url('settings', array('action'=>'disable-exams')) ?>"><span class="glyphicon glyphicon-ban-circle"></span></button>
          <?php endif; ?>
          <?php if (isset($acl) && $acl->isAllowed("enableExams")): ?>
            <button type="button" class="btn btn-default" id="enable-general-selection" data-resource="<?php echo $this->url('settings', array('action'=>'enable-exams')) ?>"><span class="glyphicon glyphicon-ok"></span></button>
          <?php endif; ?>
        </div>
    </p>
    </div>
  <?php endif; ?>

  <div id="view-general-search">
    <?php if (count($exams)): ?>
      <table class="table table-striped table-hover">
          <tr>
              <th><input id="app-general-check" type="checkbox" /></th>
              <th>Código</th>
              <th>Nombre del exámen</th>
              <th>Estado</th>
              <th>Tipo</th>
              <th>Acciones</th>
          </tr>
          <?php foreach ($exams as $exam) : ?>
          <tr>
              <td><input type="checkbox" data-selection-id="<?= $exam->cod_exa ?>" class="general-input-selection"></td>
              <td><?php echo $this->escapeHtml($exam->cod_exa);?></td>
              <td><?php echo $this->escapeHtml($exam->nom_exa);?></td>
              <td><?= ($exam->est_exa == 1) ? "Activo": "Inactivo"; ?></td>
              <td><?php 
              switch ($exam->tip_exa) {
                case 1:
                    echo "Exámenes";
                  break;
                case 2:
                    echo "Patologías";
                  break;
                case 3:
                    echo "Procedimientos Quirúrgicos";
                  break;
                case 4:
                    echo "Procedimientos no Quirúrgicos";
                  break;
                default:
                    echo "Indefinido";
                  break;
              }
              ?></td>
          <td>
            <?php if (isset($acl) && $acl->isAllowed("editExams")): ?>
              <a href="<?php echo $this->url('settings',
              array('action'=>'edit-exam', 'id' => $exam->cod_exa));?>"
              class="" title="editar"><span class="glyphicon glyphicon-pencil"></span></a>
            <?php endif; ?>
            <?php if (isset($acl) && $acl->isAllowed("disableExams")): ?>
              <a href="<?php echo $this->url('settings',
              array('action'=>'disable-exams', 'id' => $exam->cod_exa));?>"
              class="" title="deshabilitar"><span class="glyphicon glyphicon-ban-circle"></span></a>
            <?php endif; ?>
            <?php if (isset($acl) && $acl->isAllowed("enableExams")): ?>
              <a href="<?php echo $this->url('settings',
              array('action'=>'enable-exams', 'id' => $exam->cod_exa));?>"
              class="" title="habilitar"><span class="glyphicon glyphicon-ok"></span></a>
            <?php endif; ?>
            <?php if (isset($acl) && $acl->isAllowed("deleteExams")): ?>
              <a href="<?php echo $this->url('settings',
              array('action'=>'delete-exams', 'id' => $exam->cod_exa));?>"
              class="hidden" title="eliminar"><span class="glyphicon glyphicon-trash"></span></a>
            <?php endif; ?>
          </td>
          </tr>
          <?php endforeach; ?>
      </table>
    <?php elseif($empty): ?>
      <div class="panel panel-default">
        <div class="panel-body">
          Aún no se han registrado exámenes!
        </div>
      </div>
    <?php else: ?>
      <div class="panel panel-warning">
        <div class="panel-body">
          No se han encontrado exámenes que contengan la palabra <strong><?= $this->escapeHtml($needle) ?></strong>
        </div>
      </div>
    <?php endif; ?>
  </div>
<?php endif; ?>