<?php if (isset($Exception)): ?>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> <?= $Exception ?>
</div>
<?php endif; ?>

<?php if (!isset($Exception)): ?>
	<?php
	$title = 'Eliminar paciente';
	$this->headTitle($title);
	?>
	<h3><?php echo $this->escapeHtml($title); ?></h3>

	<p>Estás seguro de que deseas eliminar el paciente
		<strong><?= $this->escapeHtml($patient->pri_nom_pac." ".$patient->pri_ape_pac); ?></strong> con documento
		<strong><?php echo $this->escapeHtml($patient->num_doc_pac); ?></strong> ?
	</p>
	<?php
		$url = $this->url('admissions', array(
			'action' => 'delete-patients',
			'id'     => $this->id,
			'type'     => $this->type,
		));
	?>
	<form action="<?php echo $url; ?>" method="post">
		<div>
			<input type="hidden" name="id" value="<?php echo (string) $patient->num_doc_pac; ?>" />
			<input type="hidden" name="type" value="<?php echo (int) $patient->cod_tip_doc; ?>" />
			<input type="submit" name="del" value="Si" class="btn btn-danger" />
			<input type="submit" name="del" value="No" class="btn btn-primary" />
		</div>
	</form>
<?php endif; ?>