<?php
$title = 'Editar admisión';
$this->headTitle($title);
?>
<h3><?php echo $this->escapeHtml($title); ?></h3>

<?php if (isset($Success) and $Success): ?>
<div class="alert alert-success alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong>  La admisión ha sido actualizada satisfactoriamente
</div>
	<?php if (!$xmlHttpRequest): ?>
		<a href="<?php echo $this->url('admissions', array('action'=>'index')) ?>" class="btn btn-primary">Volver</a><br /><br />
	<?php endif; ?>
<?php endif; ?>

<?php if (isset($Exception)): ?>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> <?= $Exception ?>
</div>
<?php endif; ?>

<?php 
if (isset($form))
{
	$form = $this->form;
	$form->setAttribute(
		'action', $this->url('admissions',
		array(
			'action' => 'edit-admission',
			'id'     => $this->id,
		)
	));
	$form->prepare();

	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('cod_adm'));
	echo $this->formHidden($form->get('cod_tip_doc'));
	$form->get('cod_tip_doc')->setAttribute('disabled', 'disabled');
	echo $this->formRow($form->get('cod_tip_doc'));
	$form->get('num_doc_pac')->setAttribute('readonly', 'readonly');
	echo $this->formRow($form->get('num_doc_pac'));
	echo $this->formRow($form->get('cod_usu_med'));
	echo $this->formRow($form->get('cod_are'));
	echo $this->formRow($form->get('cod_ent'));
	echo $this->formRow($form->get('obs_adm'));
	if (!$xmlHttpRequest):
		echo $this->formSubmit($form->get('submit'));
	endif;
	echo $this->form()->closeTag();
}
?>
