<?php if (isset($Exception)): ?>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> <?= $Exception ?>
</div>
<?php endif; ?>

<?php if (!isset($Exception)): ?>
  <?php if (!$xmlHttpRequest): ?>
    <span class="glyphicon glyphicon-cog" style="font-size: 20px; color: rgb(0,150,200)"></span>
    <h3 style="display: inline-block">Administrador de pacientes</h3>
  <?php endif; ?>

  <?php if (!$xmlHttpRequest || !$simulateXmlHttpRequest): ?>
    <div id="setting-controls">
    <p>
      <div class="input-group" style="width: 215px; float: left; margin: 0 5px 0 0;">
        <input type="search" placeholder="documento" class="form-control" id="general-search" maxlength="20"
        data-url="<?php echo $this->url('admissions', array('action'=>'view-patients'));?>" autofocus="autofocus" />
        <div class="input-group-btn">
        <button type="button" id="run-general-search" class="btn btn-default" tabindex="-1" style="border-left: none;">
          <span class="glyphicon glyphicon-search"></span>
        </button>
        </div>
      </div>

      <div class="btn-group">
        <?php if (isset($acl) && $acl->isAllowed("addPatients")): ?>
          <button type="button" class="btn btn-default" id="general-add" data-resource="<?php echo $this->url('admissions', array('action'=>'add-patient')) ?>"><span class="glyphicon glyphicon-plus"></span></button>
        <?php endif; ?>
        <?php if (isset($acl) && $acl->isAllowed("deletePatients")): ?>
          <button type="button" class="btn btn-default hidden" id="del-general-selection-tpk" data-resource="<?php echo $this->url('admissions', array('action'=>'delete-patients')) ?>"><span class="glyphicon glyphicon-trash"></span></button>
        <?php endif; ?>
        <?php if (isset($acl) && $acl->isAllowed("editPatients")): ?>
          <button type="button" class="btn btn-default" id="edit-general-selection-tpk" data-resource="<?php echo $this->url('admissions', array('action'=>'edit-patient')) ?>"><span class="glyphicon glyphicon-pencil"></span></button>
        <?php endif; ?>
      </div>
    </p>
    </div>
  <?php endif; ?>

  <div id="view-general-search">
    <?php if (count($patients)): ?>
      <table class="table table-striped table-hover table-condensed">
          <tr>
              <th><input id="app-general-check" type="checkbox" /></th>
              <th>Tipo de documento</th>
              <th>Documento</th>
              <th>Nombre del paciente</th>
              <th>Acciones</th>
          </tr>
          <?php foreach ($patients as $patient) : ?>
          <tr>
              <td><input type="checkbox" data-selection-id="<?= $patient->num_doc_pac ?>" data-selection-type="<?= $patient->cod_tip_doc ?>" class="general-input-selection"></td>
              <td><?php echo $this->escapeHtml($patient->nom_tip_doc);?></td>             
              <td><?php echo $this->escapeHtml($patient->num_doc_pac);?></td>
              <td>
              <?php $name = $this->escapeHtml($patient->pri_nom_pac." ".$patient->seg_nom_pac." ".$patient->pri_ape_pac." ".$patient->seg_ape_pac); ?>
              <?php if ($acl->isAllowed("admissionPatients")): ?>
                <a href="<?php echo $this->url('admissions',
                array('action'=>'patient-admission', 'id' => $patient->num_doc_pac, 'type' => $patient->cod_tip_doc));?>"
                class="cell init-popover" title="Admisión" data-toggle="popover" data-placement="left" data-trigger="hover" data-content="Desde este enlace puedes admisionar directamente el paciente"><?= $this->escapeHtml($name) ?></a>
              <?php else: ?>
                <?= $this->escapeHtml($name) ?>
              <?php endif; ?>              
              </td>
          <td>
            <?php if (isset($acl) && $acl->isAllowed("editPatients")): ?>
                <a href="<?php echo $this->url('admissions',
                array('action'=>'edit-patient', 'id' => $patient->num_doc_pac, 'type' => $patient->cod_tip_doc));?>"
                class="" title="editar"><span class="glyphicon glyphicon-pencil"></span></a>
            <?php endif; ?>
            <?php if (isset($acl) && $acl->isAllowed("admissionPatients")): ?>
                <a href="<?php echo $this->url('admissions',
                array('action'=>'patient-admission', 'id' => $patient->num_doc_pac, 'type' => $patient->cod_tip_doc));?>"
                class="" title="admisionar"><span class="glyphicon glyphicon-pushpin"></span></a>
            <?php endif; ?>
            <?php if (isset($acl) && $acl->isAllowed("viewAdmissions")): ?>
                <a href="<?php echo $this->url('admissions',
                array('action'=>'view-admissions', 'id' => $patient->num_doc_pac, 'type' => $patient->cod_tip_doc));?>"
                class="" title="ver admisiones"><span class="glyphicon glyphicon-tasks"></span></a>
            <?php endif; ?>

            <?php 

            $folios = $history->getFoliosForPatient($patient->num_doc_pac, $patient->cod_tip_doc)->toArray();
              
              if (count($folios))
              {
                ?>
                <div class="btn-group">
                  <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                    <span class="glyphicon glyphicon-briefcase"></span> Historia <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu" role="menu" style="min-width: 100px; text-align: left">

                  <?php
                  foreach ($folios as $folio) {
                    ?>
                    <li>
                      <a target="_blank" class="$" href="<?= $this->url('medicalHistory') . '/viewHistory/' . $folio["admission"] ?>"><span class="glyphicon glyphicon-file"></span> Folio <?= $folio["folio"] ?> - <?= $folio["medico"] ?> - <?= $folio["registro"] ?></a>
                    </li>
                    <?php
                  }
                  ?>

                    </ul>
                </div>
                <?php
              }
            ?>


            <?php if (isset($acl) && $acl->isAllowed("deletePatients")): ?>
                <a href="<?php echo $this->url('admissions',
                array('action'=>'delete-patients', 'id' => $patient->num_doc_pac, 'type' => $patient->cod_tip_doc));?>"
                class="hidden" title="eliminar"><span class="glyphicon glyphicon-trash"></span></a>
            <?php endif; ?>
          </td>
          </tr>
          <?php endforeach; ?>
      </table>
    <?php elseif($empty): ?>
      <div class="panel panel-default">
        <div class="panel-body">
          Aún no se han registrado pacientes!
        </div>
      </div>
    <?php else: ?>
      <div class="panel panel-warning">
        <div class="panel-body">
          No se han encontrado pacientes que contengan <strong><?= $this->escapeHtml($needle) ?></strong>
          en su documento
        </div>
      </div>
    <?php endif; ?>
  </div>
<?php endif; ?>