<?php if (isset($Exception)): ?>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> <?= $Exception ?>
</div>
<?php endif; ?>

<?php if (!isset($Exception)): ?>
  <?php if (!$xmlHttpRequest): ?>
    <span class="glyphicon glyphicon-cog" style="font-size: 20px; color: rgb(0,150,200)"></span>
    <h3 style="display: inline-block">Administrador de admisiones</h3>
  <?php endif; ?>

  <?php if (!$xmlHttpRequest || !$simulateXmlHttpRequest): ?>
    <div id="setting-controls">
    <p>
      <div class="input-group" style="width: 215px; float: left; margin: 0 5px 0 0;">
        <input type="search" placeholder="buscar" class="form-control" id="general-search" maxlength="20"
        data-url="<?php echo $this->url('admissions', array('action'=>'view-admissions'));?>"
        data-runtime-parameters="{ 'time': $('#general-filter-search').val(), 'limit': $('#general-filter-top').val()}"
        autofocus="autofocus" />
        <div class="input-group-btn">
        <button type="button" id="run-general-search" class="btn btn-default" tabindex="-1" style="border-left: none;">
          <span class="glyphicon glyphicon-search"></span>
        </button>
        </div>
      </div>

      <select id="general-filter-search" class="form-control" style="width: 120px; float: left; margin: 0 5px 0 0;">
        <option value="0">Anteriores</option>
        <option value="1" selected="selected">Hoy</option>
      </select>

      <select id="general-filter-top" class="form-control" style="width: 90px; float: left; margin: 0 5px 0 0;">
        <option value="10">10</option>
        <option value="50">50</option>
        <option value="100" selected="selected">100</option>
        <option value="1000">1000</option>
      </select>

      <div class="btn-group">
        <?php if (isset($acl) && $acl->isAllowed("admissionPatients")): ?>
          <button type="button" class="btn btn-default" id="general-add" title="agregar" data-resource="<?php echo $this->url('admissions', array('action'=>'add-admission')) ?>"><span class="glyphicon glyphicon-plus"></span></button>
        <?php endif; ?>
        <?php if (isset($acl) && $acl->isAllowed("editAdmissions")): ?>
          <button type="button" class="btn btn-default" id="edit-general-selection" title="editar" data-resource="<?php echo $this->url('admissions', array('action'=>'edit-admission')) ?>"><span class="glyphicon glyphicon-pencil"></span></button>
        <?php endif; ?>
        <?php if (isset($acl) && $acl->isAllowed("deleteAdmissions")): ?>
          <button type="button" class="btn btn-default hidden" id="del-general-selection" title="eliminar" data-resource="<?php echo $this->url('admissions', array('action'=>'delete-admissions')) ?>"><span class="glyphicon glyphicon-trash"></span></button>
        <?php endif; ?>
        <?php if (isset($acl) && $acl->isAllowed("annulAdmissions")): ?>
          <button type="button" class="btn btn-default" id="disable-general-selection" title="anular" data-resource="<?php echo $this->url('admissions', array('action'=>'annul-admissions')) ?>"><span class="glyphicon glyphicon-ban-circle"></span></button>
        <?php endif; ?>
        <?php if (isset($acl) && $acl->isAllowed("openAdmissions")): ?>
          <button type="button" class="btn btn-default" id="enable-general-selection" title="abrir" data-resource="<?php echo $this->url('admissions', array('action'=>'open-admissions')) ?>"><span class="glyphicon glyphicon-pushpin"></span></button>
        <?php endif; ?>
        <?php if (isset($acl) && $acl->isAllowed("closeAdmissions")): ?>
          <button type="button" class="btn btn-default" id="close-selected-admissions" title="cerrar" data-resource="<?php echo $this->url('admissions', array('action'=>'close-admissions')) ?>"><span class="glyphicon glyphicon-off"></span></button>
        <?php endif; ?>
      </div>

      <div class="btn-group">
        <button type="button" class="btn btn-default" id="general-alternation-table" title="alternar vista" data-exception="[1,2,15]"><span class= "glyphicon glyphicon-list-alt"></span></button>
      </div>

    </p>
    </div>
  <?php endif; ?>

  <div id="view-general-search">
    <?php if (count($admissions)): ?>
      <table class="table table-striped table-hover table-condensed" id="admissions-table">
          <tr>
              <th><input id="app-general-check" type="checkbox" /></th>
              <th>ID *</th>
              <th>Fecha y hora</th>
              <th style="display: none">Estado</th>
              <th>Paciente *</th>
              <th style="display: none">Documento <br /> paciente *</th>
              <th style="display: none">Tipo de <br /> documento</th>
              <th style="display: none">Área</th>
              <th style="display: none">Entidad</th>
              <th>Médico *</th>
              <th style="display: none">ID <br /> médico *</th>
              <th>Usuario que <br /> admisiona</th>
              <th style="display: none">ID admisionador</th>
              <th>Observación</th>
              <th>Acciones</th>
          </tr>
          <?php foreach ($admissions as $admission) : ?>
          <tr
            <?php
              switch ($admission->est_adm):
                case "":
                    ?>class="success"<?php
                  break;
                case "A":
                    ?>class="danger"<?php
                  break;
                case "C":
                    ?><?php
                  break;
                default:
                    ?>class="danger"<?php
                  break;
              endswitch;
              ?>
          >
              <td><input type="checkbox" data-selection-id="<?= $admission->cod_adm ?>" class="general-input-selection"></td>
              <td><?= $this->escapeHtml($admission->cod_adm); ?></td>             
              <td><?= $this->escapeHtml($admission->fec_adm); ?></td>             
              <td style="display: none"><?php 
              switch ($admission->est_adm):
                case "":
                    echo "Abierta";
                  break;
                case "A":
                    echo "Anulada";
                  break;
                case "C":
                    echo "Cerrada";
                  break;
                default:
                    echo "Sin estado!";
                  break;
              endswitch;
              ?></td>
              <td>
              <?php if ($acl->isAllowed("viewHistory")): ?>
				<a href="<?php echo $this->url('medicalHistory',
                array('action'=>'admission', 'id' => $admission->cod_adm));?>"
                class="cell init-popover" title="Historia" data-toggle="popover" data-placement="left" data-trigger="hover" data-content="Desde este enlace puedes acceder directamente a la historia clínica del paciente"><?= $this->escapeHtml($admission->nom_pac) ?></a>              	
              <?php else: ?>
              	<?= $this->escapeHtml($admission->nom_pac) ?>
              <?php endif; ?>
              </td>
              <td style="display: none"><?= $this->escapeHtml($admission->num_doc_pac) ?></td>
              <td style="display: none"><?= $this->escapeHtml($admission->nom_tip_doc); ?></td>
              <td style="display: none"><?= $this->escapeHtml($admission->nom_are) ?></td>
              <td style="display: none"><?= $this->escapeHtml($admission->nom_ent) ?></td>
              <td><?= $this->escapeHtml($admission->usu_med) ?></td>
              <td style="display: none"><?= $this->escapeHtml($admission->cod_usu_med) ?></td>
              <td><?= $this->escapeHtml($admission->usu_reg) ?></td>
              <td style="display: none"><?= $this->escapeHtml($admission->cod_usu_reg) ?></td>
              <td><?= ($this->escapeHtml($admission->obs_adm) != "") ? $this->escapeHtml($admission->obs_adm) : " Ninguna "; ?></td>
          <td>
            <?php if (isset($acl) && $acl->isAllowed("editAdmissions")): ?>
                <a href="<?php echo $this->url('admissions',
                array('action'=>'edit-admission', 'id' => $admission->cod_adm));?>"
                class="" title="editar"><span class="glyphicon glyphicon-pencil"></span></a>
            <?php endif; ?>
            <?php if (isset($acl) && $acl->isAllowed("viewHistory")): ?>
                <a href="<?php echo $this->url('medicalHistory',
                array('action'=>'admission', 'id' => $admission->cod_adm));?>"
                class="viewHistory" title="historia clínica"><span class="glyphicon glyphicon-folder-open"></span></a>
            <?php endif; ?>
            <?php if (isset($acl) && $acl->isAllowed("deleteAdmissions")): ?>
                <a href="<?php echo $this->url('admissions',
                array('action'=>'delete-admissions', 'id' => $admission->cod_adm));?>"
                class="hidden" title="eliminar"><span class="glyphicon glyphicon-trash"></span></a>
            <?php endif; ?>
          </td>
          </tr>
          <?php endforeach; ?>
      </table>
    <?php elseif($empty): ?>
      <div class="panel panel-default">
        <div class="panel-body">
          Aún no se han registrado admisiones!
        </div>
      </div>
    <?php else: ?>
      <div class="panel panel-warning">
        <div class="panel-body">
          No se han encontrado admisiones que contengan <strong><?= $this->escapeHtml($needle) ?></strong>
          en alguno de sus campos
        </div>
      </div>
    <?php endif; ?>
  </div>
<?php endif; ?>