<?php
$title = 'Agregar usuario';
$this->headTitle($title);
?>

<h3><?php echo $this->escapeHtml($title); ?></h3><?php

if (isset($Success) and $Success): ?>
<div class="alert alert-success alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong>  El usuario ha sido registrado satisfactoriamente
</div>
<?php endif;

if (isset($Exception)): ?>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> <?= $Exception ?>
</div>
<?php endif;

if (isset($form)):
	$form->setAttribute('action', $this->url('auth', array('action' => 'add')));
	$form->prepare();
	echo $this->form()->openTag($form);
	echo $this->formRow($form->get('cod_usu'));
	echo $this->formRow($form->get('nom_usu'));
	echo $this->formRow($form->get('pas_usu'));
	echo $this->formRow($form->get('cod_per'));
	echo $this->formRow($form->get('est_usu'));
	if (!$xmlHttpRequest):
		echo $this->formSubmit($form->get('submit'));
	endif;
	echo $this->form()->closeTag();
endif;
