<?php if (isset($Exception)): ?>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> <?= $Exception ?>
</div>
<?php endif; ?>

<?php if (!$xmlHttpRequest): ?>
	<a href="<?php echo $this->url('auth', array('action'=>'view-users')) ?>" class="btn btn-primary">Volver</a><br /><br />
<?php endif; ?>

<?php if (!isset($Exception)): ?>
	<?php
	$title = 'Eliminar usuario';
	$this->headTitle($title);
	?>
	<h1><?php echo $this->escapeHtml($title); ?></h1>

	<p>Estás seguro de que deseas eliminar el usuario
		<strong><?php echo $this->escapeHtml($user->nom_usu); ?></strong> con id
		<strong><?php echo $this->escapeHtml($user->cod_usu); ?></strong> ?
	</p>
	<?php
		$url = $this->url('auth', array(
			'action' => 'delete',
			'id'     => $this->id,
		));
	?>
	<form action="<?php echo $url; ?>" method="post">
		<div>
			<input type="hidden" name="id" value="<?= (string) $user->cod_usu; ?>" />
			<input type="submit" name="del" value="Si" class="btn btn-danger" />
			<input type="submit" name="del" value="No" class="btn btn-primary" />
		</div>
	</form>
<?php endif; ?>