<?php if (isset($Exception)): ?>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> <?= $Exception ?>
</div>
<?php endif; ?>

<?php if (!isset($Exception)): ?>
  <?php if (!$xmlHttpRequest): ?>
    <span class="glyphicon glyphicon-user" style="font-size: 20px; color: rgb(0,150,200)"></span>
    <h3 style="display: inline-block">Administrador de usuarios</h3>
  <?php endif; ?>

  <?php if (!$xmlHttpRequest || !$simulateXmlHttpRequest): ?>
    <div class="settings-controls">
    <p>
        <div class="input-group" style="width: 200px; float: left; margin: 0 5px 0 0;">
            <input type="search" placeholder="búsqueda" class="form-control" id="general-search" 
            data-url="<?php echo $this->url('auth', array('action'=>'view-users'));?>" autofocus="autofocus" />
            <div class="input-group-btn">
            <button type="button" id="run-general-search" class="btn btn-default" tabindex="-1" style="border-left: none;">
                <span class="glyphicon glyphicon-search"></span>
            </button>
            </div>
        </div>

        <div class="btn-group">
          <?php if (isset($acl) && $acl->isAllowed("addUsers")): ?>
              <button type="button" class="btn btn-default" id="general-add" data-resource="<?php echo $this->url('auth', array('action'=>'add')) ?>"><span class="glyphicon glyphicon-user"></span></button>
          <?php endif; ?>
          <?php if (isset($acl) && $acl->isAllowed("editUsers")): ?>
              <button type="button" class="btn btn-default" id="edit-general-selection" data-resource="<?php echo $this->url('auth', array('action'=>'edit')) ?>"><span class="glyphicon glyphicon-pencil"></span></button>
          <?php endif; ?>
          <?php if (isset($acl) && $acl->isAllowed("deleteUsers")): ?>
              <button type="button" class="btn btn-default hidden" id="del-general-selection" data-resource="<?php echo $this->url('auth', array('action'=>'delete')) ?>"><span class="glyphicon glyphicon-trash"></span></button>
          <?php endif; ?>
          <?php if (isset($acl) && $acl->isAllowed("disableUsers")): ?>          
              <button type="button" class="btn btn-default" id="disable-general-selection" data-resource="<?php echo $this->url('auth', array('action'=>'disable')) ?>"><span class="glyphicon glyphicon-ban-circle"></span></button>
          <?php endif; ?>
          <?php if (isset($acl) && $acl->isAllowed("enableUsers")): ?>          
              <button type="button" class="btn btn-default" id="enable-general-selection" data-resource="<?php echo $this->url('auth', array('action'=>'enable')) ?>"><span class="glyphicon glyphicon-ok"></span></button>
          <?php endif; ?>
        </div>
    </p>
    </div>
  <?php endif; ?>

  <div id="view-general-search">
    <?php if (count($users)): ?>
      <table class="table table-striped table-hover">
          <tr>
              <th><input id="app-general-check" type="checkbox" /></th>
              <th>Identificador</th>
              <th>Nombre de usuario</th>
              <th>Permiso</th>
              <th>Estado</th>
              <th>Registro</th>
              <th>Acciones</th>
          </tr>
          <?php foreach ($users as $user) : ?>
          <tr>
              <td><input type="checkbox" data-selection-id="<?= $user->cod_usu ?>" class="general-input-selection"></td>
              <td><?php echo $this->escapeHtml($user->cod_usu);?></td>
              <td><?php echo $this->escapeHtml($user->nom_usu);?></td>
              <td><?= ($user->nom_per == '' || empty($user->nom_per)) ? "No asignado": $this->escapeHtml($user->nom_per);?></td>
              <td><?= ($user->est_usu == 1) ? "Activo": "Inactivo"; ?></td>
              <td><?php echo $this->escapeHtml($user->fec_reg_usu);?></td>
          <td>
            <?php if (isset($acl) && $acl->isAllowed("editUsers")): ?>
                <a href="<?php echo $this->url('auth',
                array('action'=>'edit', 'id' => $user->cod_usu));?>"
                class="" title="editar"><span class="glyphicon glyphicon-pencil"></span></a>
            <?php endif; ?>
            <?php if (isset($acl) && $acl->isAllowed("disableUsers")): ?>
                <a href="<?php echo $this->url('auth',
                array('action'=>'disable', 'id' => $user->cod_usu));?>"
                class="" title="bloquear"><span class="glyphicon glyphicon-ban-circle"></span></a>
            <?php endif; ?>
            <?php if (isset($acl) && $acl->isAllowed("enableUsers")): ?>
                <a href="<?php echo $this->url('auth',
                array('action'=>'enable', 'id' => $user->cod_usu));?>"
                class="" title="Activar"><span class="glyphicon glyphicon-ok"></span></a>
            <?php endif; ?>
            <?php if (isset($acl) && $acl->isAllowed("deleteUsers")): ?>
                <a href="<?php echo $this->url('auth',
                array('action'=>'delete', 'id' => $user->cod_usu));?>"
                class="hidden" title="Eliminar"><span class="glyphicon glyphicon-trash"></span></a>
            <?php endif; ?>
          </td>
          </tr>
          <?php endforeach; ?>
      </table>
    <?php elseif($empty): ?>
    <div class="panel panel-default">
      <div class="panel-body">
        Aún no se han registrado Usuarios!
      </div>
    </div>
    <?php else: ?>
    <div class="panel panel-default">
      <div class="panel-body">
        No se han encontrado usuarios que contengan la palabra <strong><?= $this->escapeHtml($needle) ?></strong>
      </div>
    </div>
    <?php endif; ?>
  </div>
<?php endif; ?>