<?php if (isset($Exception)): ?>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> <?= $Exception ?>
</div>

<?php else: ?>

    <?php if (count($admission) && isset($open) && $open): ?>

        <?php if (isset($Success) && $Success): ?>
        <div class="alert alert-success alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> Se ha guardado satisfactoriamente el diagnóstico </strong>
        </div>
            <?php if (!$xmlHttpRequest): ?>
                <a href="<?php echo $this->url('medicalHistory', array('action'=>'addHistory', 'id' => $admission->cod_adm)); ?>" class="btn btn-default">Regresar</a>
                <br /><br />
            <?php endif; ?>
        <?php endif; ?>

    <?php elseif (isset($open) && !$open): ?>
    <div class="alert alert-warning alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> La admisión no está abierta!
    </div>
    <?php endif; ?>
<?php endif; ?>

<?php
$title = 'Nuevo Diagnóstico';
$this->headTitle($title);
?>

<h3>
    <?php echo $this->escapeHtml($title); ?>
</h3>

<?php
if (isset($form)):
    $form->setAttribute("class", "plts-form label-inline");
    $form->setAttribute('action', $this->url('medicalHistory', array('action' => 'addDiagnostic')));
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('cod_dia'));
    $form->get('nom_dia')->setAttribute("data-resource", $this->url('medicalHistory', array('action'=>'searchDiagnostic', 'id' => $admission->cod_adm)));
    echo $this->formRow($form->get('nom_dia'));
    ?> <div class="radio"> <?php
    echo $this->formRow($form->get('dia_pri'));
    ?> </div> <?php
    echo $this->formRow($form->get('tip_dia'));
    echo $this->formRow($form->get('clasi_dia'));
    echo $this->formRow($form->get('clase_dia'));
    ?><br /><div class="checkbox"> <?php
    echo $this->formRow($form->get('dia_ing'));
    ?> </div> <?php
    ?> <div class="checkbox"> <?php
    echo $this->formRow($form->get('dia_egr'));
    ?> </div> <?php
    echo $this->formRow($form->get('obs_dia'));
    if (!$xmlHttpRequest):
        echo $this->formSubmit($form->get('submit'));
    endif;
    echo $this->form()->closeTag();
endif;
?>

<h3>Diagnósticos registrados</h3>


    <div id="setting-controls">
        <p>
        <div class="btn-group">
          <button type="button" class="btn btn-default" id="run-diagnostic-refresh" title="actualizar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'view-diagnostics', 'id' => $admission->cod_adm)) ?>"><span class="glyphicon glyphicon-refresh"></span></button>
          <button type="button" class="btn btn-default" id="edit-selected-diagnostics" title="editar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'edit-diagnostic', 'id' => $admission->cod_adm)) ?>"><span class="glyphicon glyphicon-pencil"></span></button>
          <button type="button" class="btn btn-default" id="delete-selected-diagnostics" title="eliminar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'delete-diagnostics', 'id' => $admission->cod_adm)) ?>"><span class="glyphicon glyphicon-trash"></span></button>
        </div>

        <div class="btn-group">
          <button type="button" class="btn btn-default" id="diagnostics-alternation-table" title="alternar vista" data-exception="[1,2]"><span class= "glyphicon glyphicon-list-alt"></span></button>
        </div>
        </p>
    </div>

<div id="view-diagnostics">
<?php if (count($diagnostics)): ?>
    <table class="table table-striped table-hover table-condensed" id="diagnostics-table">
        <tr>
            <th><input id="app-diagnostics-check" type="checkbox" /></th>
            <th>Diagnóstico</th>
            <th>Principal</th>
            <th style="display: none">Tipo</th>
            <th style="display: none">Clasificación</th>
            <th style="display: none">Clase</th>
            <th>Ingreso</th>
            <th>Egreso</th>
            <th>Observaciones</th>
        </tr>   
        <?php foreach ($diagnostics as $diagnostic) : ?>
        <tr>
            <td><input type="checkbox" data-selection-id="<?= $diagnostic->cod_dia ?>" class="diagnostic"></td>
            <td><?= $this->escapeHtml($diagnostic->nom_dia);?> </td>           
            <td><?php
                switch ($diagnostic->dia_pri) {
                    case 0:
                        echo "No";
                        break;
                    case 1:
                        echo "Si";
                        break;
                    default:
                        echo "Indefinido";
                        break;
                }
            ?></td>           
            <td style="display: none"><?php
                switch ($diagnostic->tip_dia) {
                    case 1:
                        echo "Presuntivo";
                        break;
                    case 2:
                        echo "Definitivo";
                        break;
                    default:
                        echo "Indefinido";
                        break;
                }
            ?></td>
            <td style="display: none"><?php
                switch ($diagnostic->clasi_dia) {
                    case 1:
                        echo "Impresión diagnóstico";
                        break;
                    case 2:
                        echo "Confirmado nuevo";
                        break;
                    case 3:
                        echo "Confirmado nuevo";
                        break;
                    default:
                        echo "Indefinido";
                        break;
                }
            ?></td>
            <td style="display: none"><?php
                switch ($diagnostic->clase_dia) {
                    case 1:
                        echo "Preoperatorio";
                        break;
                    case 2:
                        echo "Postoperatorio";
                        break;
                    case 3:
                        echo "Histopatológico";
                        break;
                    case 4:
                        echo "No corresponde";
                        break;
                    default:
                        echo "Indefinido";
                        break;
                }
            ?></td>
            <td><?= ($diagnostic->dia_ing) ? "Si" : "No" ?></td>
            <td><?= ($diagnostic->dia_egr) ? "Si" : "No" ?></td>
            <td><?php $obs = trim($diagnostic->obs_dia); if (empty($obs)) echo "Ninguna"; else echo $this->escapeHtml($obs) ?></td>
        </tr>
        <?php endforeach; ?>
    </table>
<?php else: ?>
    <div class="panel panel-warning">
        <div class="panel-body">
        Aún no se han registrado diagnósticos
        </div>
    </div>
<?php endif; ?>
</div>