<?php if (isset($Exception)): ?>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> <?= $Exception ?>
</div>

<?php else: ?>

    <?php if (count($admission) && isset($open) && $open): ?>

        <?php if (isset($Success) && $Success): ?>
        <div class="alert alert-success alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> Se ha guardado satisfactoriamente el medicamento </strong>
        </div>
            <?php if (!$xmlHttpRequest): ?>
                <a href="<?php echo $this->url('medicalHistory', array('action'=>'addHistory', 'id' => $admission->cod_adm)); ?>" class="btn btn-default">Regresar</a>
                <br /><br />
            <?php endif; ?>
        <?php endif; ?>

    <?php elseif (isset($open) && !$open): ?>
    <div class="alert alert-warning alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> La admisión no está abierta!
    </div>
    <?php endif; ?>
<?php endif; ?>

<?php
$title = 'Nuevo Medicamento';
$this->headTitle($title);
?>

<h3>
    <?php echo $this->escapeHtml($title); ?>
</h3>

<?php
if (isset($form)):
    $form->setAttribute("class", "plts-form label-inline");
    $form->setAttribute('action', $this->url('medicalHistory', array('action' => 'addMedication')));
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('cod_med'));
    $form->get('nom_med')->setAttribute("data-resource", $this->url('medicalHistory', array('action'=>'searchMedication', 'id' => $admission->cod_adm)));
    echo $this->formRow($form->get('nom_med'));
    echo $this->formRow($form->get('can_med'));
    echo $this->formRow($form->get('num_dia'));
    echo $this->formRow($form->get('ter_med'));
    echo $this->formRow($form->get('cod_apl_med'));
    echo $this->formRow($form->get('pos_med'));
    if (!$xmlHttpRequest):
        echo $this->formSubmit($form->get('submit'));
    endif;
    echo $this->form()->closeTag();
endif;
?>

<h3>Medicamentos registrados</h3>


    <div id="setting-controls">
        <p>
        <div class="btn-group">
          <button type="button" class="btn btn-default" id="run-medication-refresh" title="actualizar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'view-medications', 'id' => $admission->cod_adm)) ?>"><span class="glyphicon glyphicon-refresh"></span></button>
          <button type="button" class="btn btn-default" id="edit-selected-medications" title="editar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'edit-medication', 'id' => $admission->cod_adm)) ?>"><span class="glyphicon glyphicon-pencil"></span></button>
          <button type="button" class="btn btn-default" id="delete-selected-medications" title="eliminar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'delete-medications', 'id' => $admission->cod_adm)) ?>"><span class="glyphicon glyphicon-trash"></span></button>
        </div>

        <div class="btn-group">
          <button type="button" class="btn btn-default" id="medications-alternation-table" title="alternar vista" data-exception="[1,2]"><span class= "glyphicon glyphicon-list-alt"></span></button>
        </div>
        </p>
    </div>

<div id="view-medications">
<?php if (count($medications)): ?>
    <table class="table table-striped table-hover table-condensed" id="medications-table">
        <tr>
            <th><input id="app-medications-check" type="checkbox" /></th>
            <th>Medicamento</th>
            <th>Cantidad</th>
            <th style="display: none">Número de días</th>
            <th style="display: none">Terminación</th>
            <th>Aplicación</th>
            <th>Posología</th>
        </tr>   
        <?php foreach ($medications as $medication) : ?>
        <tr>
            <td><input type="checkbox" data-selection-id="<?= $medication->cod_med ?>" class="medication"></td>
            <td><?= $this->escapeHtml($medication->nom_med); ?> </td>           
            <td><?= $this->escapeHtml($medication->can_med); ?></td>           
            <td style="display: none"><?= $this->escapeHtml($medication->num_dia); ?></td>
            <td style="display: none"><?php  
                switch ($medication->ter_med) {
                    case 1:
                        echo "Definida";
                        break;
                    case 1:
                        echo "Indefinida";
                        break;                    
                    default:
                        echo "Indefinido";
                        break;
                }
            ?></td>
            <td><?php
                switch ($medication->cod_apl_med) {
                    case 1:
                        echo "Endovenosa";
                        break;
                    case 2:
                        echo "Enteral";
                        break;
                    case 3:
                        echo "Infusión";
                        break;
                    case 4:
                        echo "Intradérmica";
                        break;
                    case 5:
                        echo "Intramuscular";
                        break;
                    case 6:
                        echo "Intrarectal";
                        break;
                    case 7:
                        echo "Intravenosa";
                        break;
                    case 8:
                        echo "Oftalmica";
                        break;
                    case 9:
                        echo "Oral";
                        break;
                    case 10:
                        echo "Oral sonda";
                        break;
                    case 11:
                        echo "Oral succión";
                        break;
                    case 12:
                        echo "Otros";
                        break;
                    case 13:
                        echo "Parenteral";
                        break;
                    case 14:
                        echo "Respiratoria";
                        break;
                    case 15:
                        echo "Subcutánea";
                        break;
                    case 16:
                        echo "Todas las vías";
                        break;
                    case 17:
                        echo "Tópico";
                        break;
                    default:
                        echo "Indefinido";
                        break;
                }
            ?></td>
            <td><?php $obs = trim($medication->pos_med); if (empty($obs)) echo "Ninguna"; else echo $this->escapeHtml($obs) ?></td>
        </tr>
        <?php endforeach; ?>
    </table>
<?php else: ?>
    <div class="panel panel-warning">
        <div class="panel-body">
        Aún no se han registrado medicamentos
        </div>
    </div>
<?php endif; ?>
</div>