<?php if (isset($Exception)): ?>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> <?= $Exception ?>
</div>

<?php else: ?>

    <?php if (count($admission) && isset($open) && $open): ?>

        <?php if (isset($Success) && $Success): ?>
        <div class="alert alert-success alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> Se ha guardado satisfactoriamente el antecedente </strong>
        </div>
            <?php if (!$xmlHttpRequest): ?>
                <a href="<?php echo $this->url('medicalHistory', array('action'=>'addHistory', 'id' => $admission->cod_adm)); ?>" class="btn btn-default">Regresar</a>
                <br /><br />
            <?php endif; ?>
        <?php endif; ?>

    <?php elseif (isset($open) && !$open): ?>
    <div class="alert alert-warning alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> La admisión no está abierta!
    </div>
    <?php endif; ?>
<?php endif; ?>

<?php
$title = 'Nuevo antecedente';
$this->headTitle($title);
?>

<h3>
    <?php echo $this->escapeHtml($title); ?>
</h3>

<?php
if (isset($form)):
    $form->setAttribute("class", "plts-form label-inline");
    $form->setAttribute('action', $this->url('medicalHistory', array('action' => 'addBackground')));
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('cod_tip_doc'));
    $form->get('cod_tip_doc')->setAttribute("disabled", "disabled")->setLabelAttributes(array('style' => 'float: left'));
    echo $this->formRow($form->get('cod_tip_doc'));
    $form->get('num_doc_pac')->setAttribute("readonly", "readonly");
    echo $this->formRow($form->get('num_doc_pac'));
    $form->get('usu_reg')->setAttribute("readonly", "readonly");
    echo $this->formHidden($form->get('usu_reg'));
    echo $this->formRow($form->get('tip_ant'));
    echo $this->formRow($form->get('des_ant'));
    if (!$xmlHttpRequest):
        echo $this->formSubmit($form->get('submit'));
    endif;
    echo $this->form()->closeTag();
endif;
?>

<h3>Antecedentes registrados</h3>

    <div id="setting-controls">
        <p>
        <div class="btn-group">
          <button type="button" class="btn btn-default" id="run-background-refresh" title="actualizar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'view-backgrounds', 'id' => $admission->cod_adm)) ?>"><span class="glyphicon glyphicon-refresh"></span></button>
          <button type="button" class="btn btn-default hidden" id="edit-selected-backgrounds" title="editar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'edit-background', 'id' => $admission->cod_adm)) ?>"><span class="glyphicon glyphicon-pencil"></span></button>
          <button type="button" class="btn btn-default hidden" id="delete-selected-backgrounds" title="eliminar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'delete-backgrounds', 'id' => $admission->cod_adm)) ?>"><span class="glyphicon glyphicon-trash"></span></button>
        </div>
        </p>
    </div>

<div id="view-backgrounds">
<?php if (count($backgrounds)): ?>
    <table class="table table-striped table-hover table-condensed" id="backgrounds-table">
        <tr>
            <th><input id="app-backgrounds-check" type="checkbox" /></th>
            <th>Fecha</th>
            <th>Tipo</th>
            <th>Detalle</th>
        </tr>   
        <?php foreach ($backgrounds as $background) : ?>
        <tr>
            <td><input type="checkbox" data-selection-id="<?= $background->cod_ant ?>" class="background"></td>
            <td><?= $this->escapeHtml($background->fec_reg); ?> </td>
            <td><?php
            switch ($background->tip_ant) {
                case 1:
                    echo "Médicos";
                    break;
                case 2:
                    echo "Quirúrgicos";
                    break;
                case 3:
                    echo "Transfusionables";
                    break;
                case 4:
                    echo "Tóxicos";
                    break;
                case 5:
                    echo "Inmunológicos";
                    break;
                case 6:
                    echo "Alérgicos";
                    break;
                case 7:
                    echo "Traumáticos";
                    break;
                case 8:
                    echo "Psiquiátricos";
                    break;
                case 9:
                    echo "Ginecológicos";
                    break;
                case 10:
                    echo "Farmacológicos";
                    break;
                case 11:
                    echo "Familiares";
                    break;
                case 12:
                    echo "Psicológicos";
                    break;
                case 13:
                    echo "Otros";
                    break;
                default:
                    echo "Indefinido";
                    break;
            }
            ?></td>       
            <td><?php $obs = trim($background->des_ant); if (empty($obs)) echo "Ninguna"; else echo $this->escapeHtml($obs) ?></td>
        </tr>
        <?php endforeach; ?>
    </table>
<?php else: ?>
    <div class="panel panel-warning">
        <div class="panel-body">
        Aún no se han registrado antecedentes
        </div>
    </div>
<?php endif; ?>
</div>