<?php if (isset($Exception)): ?>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> <?= $Exception ?>
</div>

<?php else: ?>

    <?php if (count($admission) && isset($open) && $open): ?>

        <?php if (isset($Success) && $Success): ?>
        <div class="alert alert-success alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> Se ha guardado satisfactoriamente la indicación </strong>
        </div>
            <?php if (!$xmlHttpRequest): ?>
                <a href="<?php echo $this->url('medicalHistory', array('action'=>'addHistory', 'id' => $admission->cod_adm)); ?>" class="btn btn-default">Regresar</a>
                <br /><br />
            <?php endif; ?>
        <?php endif; ?>

    <?php elseif (isset($open) && !$open): ?>
    <div class="alert alert-warning alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> La admisión no está abierta!
    </div>
    <?php endif; ?>
<?php endif; ?>

<?php
$title = 'Nueva indicación';
$this->headTitle($title);
?>

<h3>
    <?php echo $this->escapeHtml($title); ?>
</h3>

<?php
if (isset($form)):
    $form->setAttribute('action', $this->url('medicalHistory', array('action' => 'addIndication')));
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('indicacion'));
    if (!$xmlHttpRequest):
        echo $this->formSubmit($form->get('submit'));
    endif;
    echo $this->form()->closeTag();
endif;
?>

<h3>Indicaciones registradas</h3>


    <div id="setting-controls">
        <p>
        <div class="btn-group">
          <button type="button" class="btn btn-default" id="run-indication-refresh" title="actualizar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'view-indications', 'id' => $admission->cod_adm)) ?>"><span class="glyphicon glyphicon-refresh"></span></button>
          <button type="button" class="btn btn-default" id="edit-selected-indications" title="editar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'edit-indication', 'id' => $admission->cod_adm)) ?>"><span class="glyphicon glyphicon-pencil"></span></button>
          <button type="button" class="btn btn-default" id="delete-selected-indications" title="eliminar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'delete-indications', 'id' => $admission->cod_adm)) ?>"><span class="glyphicon glyphicon-trash"></span></button>
        </div>
        </p>
    </div>

<div id="view-indications">
<?php if (count($indications)): ?>
    <table class="table table-striped table-hover table-condensed" id="indications-table">
        <tr>
            <th><input id="app-indications-check" type="checkbox" /></th>
            <th>Código</th>
            <th>Detalle de la indicación</th>
        </tr>
        <?php foreach ($indications as $indication) : ?>
        <tr>
            <td><input type="checkbox" data-selection-id="<?= $indication->cod_ind ?>" class="indication"></td>
            <td><?= $this->escapeHtml($indication->cod_ind); ?> </td>
            <td><?php $obs = trim($indication->indicacion); if (empty($obs)) echo "Ninguna"; else echo $this->escapeHtml($obs) ?></td>
        </tr>
        <?php endforeach; ?>
    </table>
<?php else: ?>
    <div class="panel panel-warning">
        <div class="panel-body">
        Aún no se han registrado indicaciones
        </div>
    </div>
<?php endif; ?>
</div>