<?php if (isset($Exception)): ?>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> <?= $Exception ?>
</div>

<?php else: ?>

    <?php if (count($admission) && isset($open) && $open): ?>

        <?php if (isset($Success) && $Success): ?>
        <div class="alert alert-success alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> Se ha guardado satisfactoriamente la solicitud </strong>
        </div>
            <?php if (!$xmlHttpRequest): ?>
                <a href="<?php echo $this->url('medicalHistory', array('action'=>'addHistory', 'id' => $admission->cod_adm)); ?>" class="btn btn-default">Regresar</a>
                <br /><br />
            <?php endif; ?>
        <?php endif; ?>

    <?php elseif (isset($open) && !$open): ?>
    <div class="alert alert-warning alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> La admisión no está abierta!
    </div>
    <?php endif; ?>
<?php endif; ?>

<?php
$title = 'Nueva Solicitud ';
switch ($type) {
    case 1:
        $str = "Exámen";
        break;
    case 2:
        $str = "Patología";
        break;
    case 3:
        $str = "Procedimiento quirúrgico";
        break;
    case 4:
        $str = "Procedimiento no quirúrgico";
        break;
    default:
        $str = "Indefinida";
        break;
}
$title .= "(".$str.")";
$this->headTitle($title);
?>

<h3>
    <?php echo $this->escapeHtml($title); ?>
</h3>

<?php
if (isset($form)):
    $form->setAttribute("class", "plts-form label-inline");
    $form->setAttribute('action', $this->url('medicalHistory', array('action' => 'addMedication')));
    $form->prepare();
    echo $this->form()->openTag($form);
    if ($type == 1)
        $form->get('cod_exa')->setAttribute("id", "exam_solicitude_id");
    elseif ($type == 2)
        $form->get('cod_exa')->setAttribute("id", "pathology_solicitude_id");
    elseif ($type == 3)
        $form->get('cod_exa')->setAttribute("id", "proc_qx_solicitude_id");
    elseif ($type == 4)
        $form->get('cod_exa')->setAttribute("id", "proc_solicitude_id");
    echo $this->formHidden($form->get('cod_exa'));
    $form->get('nom_exa')->setAttribute("data-resource", $this->url('medicalHistory', array('action'=>'searchSolicitude', 'id' => $admission->cod_adm, 'type' => $type)));
    if ($type == 1)
        $form->get('nom_exa')->setAttribute("id", "examSolicitudeSuggestion");
    if ($type == 2)
        $form->get('nom_exa')->setAttribute("id", "pathologySolicitudeSuggestion");
    if ($type == 3)
        $form->get('nom_exa')->setAttribute("id", "procQxSolicitudeSuggestion");
    if ($type == 4)
        $form->get('nom_exa')->setAttribute("id", "procSolicitudeSuggestion");
    echo $this->formRow($form->get('nom_exa'));
    echo $this->formRow($form->get('can_exa'));
    echo $this->formRow($form->get('est_exa'));
    echo $this->formRow($form->get('obs_exa'));
    if (!$xmlHttpRequest):
        echo $this->formSubmit($form->get('submit'));
    endif;
    echo $this->form()->closeTag();
endif;
?>


<?php
    switch ($type) {
        case 1:
            $_type = "exam";
            break;
        case 2:
            $_type = "pathology";
            break;        
        case 3:
            $_type = "proc-qx";
            break;
        case 4:
            $_type = "proc";
            break;
    }
?>

<h3>Solicitudes de <?= $str ?> registradas</h3>


    <div id="setting-controls">
        <p>
        <div class="btn-group">
          <button type="button" class="btn btn-default" id="run-<?= $_type ?>-solicitude-refresh" title="actualizar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'view-solicitudes', 'id' => $admission->cod_adm, 'type' => $type)) ?>"><span class="glyphicon glyphicon-refresh"></span></button>
          <button type="button" class="btn btn-default" id="edit-selected-<?= $_type ?>-solicitudes" title="editar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'edit-solicitude', 'id' => $admission->cod_adm, 'type' => $type)) ?>"><span class="glyphicon glyphicon-pencil"></span></button>
          <button type="button" class="btn btn-default" id="delete-selected-<?= $_type ?>-solicitudes" title="eliminar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'delete-solicitudes', 'id' => $admission->cod_adm, 'type' => $type)) ?>"><span class="glyphicon glyphicon-trash"></span></button>
        </div>
        </p>
    </div>

<div id="view-<?= $_type ?>-solicitudes">
<?php if (count($solicitudes)): ?>
    <table class="table table-striped table-hover table-condensed" id="<?= $_type ?>-solicitudes-table">
        <tr>
            <th><input id="app-<?= $_type ?>-solicitudes-check" type="checkbox" /></th>
            <th>Nombre</th>
            <th>Cantidad</th>
            <th>Estado</th>
            <th>Observación</th>
        </tr>   
        <?php foreach ($solicitudes as $solicitude) : ?>
        <tr>
            <td><input type="checkbox" data-selection-id="<?= $solicitude->cod_exa ?>" class="<?= $_type ?>-solicitude"></td>
            <td><?= $this->escapeHtml($solicitude->nom_exa); ?></td>
            <td><?= $this->escapeHtml($solicitude->can_exa); ?></td>
            <td><?php  
                switch ($solicitude->est_exa) {
                    case 1:
                        echo "Rutinaria";
                        break;
                    case 2:
                        echo "Urgente";
                        break;                    
                    default:
                        echo "Indefinida";
                        break;
                }
            ?></td>
            <td><?php $obs = trim($solicitude->obs_exa); if (empty($obs)) echo "Ninguna"; else echo $this->escapeHtml($obs) ?></td>
        </tr>
        <?php endforeach; ?>
    </table>
<?php else: ?>
    <div class="panel panel-warning">
        <div class="panel-body">
        Aún no se han registrado exámenes
        </div>
    </div>
<?php endif; ?>
</div>