<?php

$title = 'Editar Incapacidad';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute(
	'action', $this->url('medicalHistory',
	array(
		'action' => 'edit-incapacity',
		'id'     => $this->id,
	)
));
$form->prepare();

if (isset($Success) and $Success): ?>
<div class="alert alert-success alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong>  La incapacidad ha sido actualizada satisfactoriamente
</div>
	<?php if (!$xmlHttpRequest): ?>
		<a href="<?php echo $this->url('medicalHistory', array('action'=>'addHistory', 'id' => $admission->cod_adm)) ?>" class="btn btn-primary">Volver</a><br /><br />
	<?php endif; ?>
<?php endif;

if (isset($Exception)): ?>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> <?= $Exception ?>
</div>
<?php endif;

$form->setAttribute("class", "plts-form label-inline");
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('cod_dia'));
echo $this->formHidden($form->get('nom_dia'));
$form->get('nom_dia')->setAttribute("disabled", "disabled");
echo $this->formRow($form->get('nom_dia'));
echo $this->formRow($form->get('fec_ini_inc'));
echo $this->formRow($form->get('num_dia_inc'));
echo $this->formRow($form->get('des_inc'));
if (!$xmlHttpRequest):
	echo $this->formSubmit($form->get('submit'));
endif;
echo $this->form()->closeTag();