<?php if (isset($Exception)): ?>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> <?= $Exception ?>
</div>
<?php endif; ?>

<?php if (!isset($Exception)): ?>
    <?php
    $title = 'Historia Clínica';
    $this->headTitle($title);
    ?>

    <a href="<?php echo $this->url('medicalHistory', array('action'=>'index')); ?>">
      <span class="glyphicon glyphicon-dashboard" style="font-size: 25px; color: rgb(0,150,200)" title="Historia médica"></span>
    </a>
    <h1 style="display: inline-block"><?php echo $this->escapeHtml($title); ?></h1>

    <h4 style="display: none;">Primera vez</h4>

    <div style="display: none;" id="view-first-histories">
    <?php if (count($firstHistory)): ?>
        <table class="table table-striped table-hover table-condensed" id="first-history-table">
            <tr>
                <th><a href="#" id="app-first-histories-check"><span class="glyphicon glyphicon-unchecked"></span></a></th>
                <th>ID</th>
                <th>Ingreso</th>
                <th>Nombre</th>
                <th>Documento</th>
                <th>Tipo de <br /> documento</th>
                <th>Folio</th>
                <th>Acciones</th>
            </tr>
            <?php foreach ($firstHistory as $history) : ?>
            <tr
                <?php if (trim($history->est_adm) == ''): echo "class='success'"; endif; ?>
                <?php if (trim($history->est_adm) == 'A'): echo "class='danger'"; endif; ?>
            >
                <td><input type="checkbox" data-selection-id="<?= $history->num_doc_pac ?>" class="first-history"></td>
                <td><?= $this->escapeHtml($history->cod_adm); ?></td>
                <td><?= $this->escapeHtml($history->fecha_reg); ?> </td>
                <td><a class='cell' href='<?= $this->url('medicalHistory', array('action'=>'viewHistory', 'id' => $history->cod_adm)) ?>'><?= $this->escapeHtml($history->nom_pac); ?></a> </td>
                <td><?= $this->escapeHtml($history->num_doc_pac); ?> </td>
                <td><?= $this->escapeHtml($history->nom_tip_doc); ?> </td>
                <td><span class='label label-info'><?= $this->escapeHtml($history->num_fol); ?></span> </td>
                <td>




                <a data-resource="<?php echo $this->url('admissions', array('action'=>'add-admission')) ?>" id="general-add"  class="btn btn-xs btn-warning"  title="Ver"><span class="glyphicon glyphicon-edit"></span> RIA</a>

                    <a href="<?php echo $this->url('medicalHistory', array('action'=>'viewHistory', 'id' => $history->cod_adm)) ?>" class="btn btn-xs btn-primary" role="button" title="Ver"><span class="glyphicon glyphicon-briefcase"></span> Ver</a>

                    <div class="btn-group">
                      <button type="button" class="btn btn-info btn-xs dropdown-toggle" data-toggle="dropdown">
                        <span style="font-size: 14px" class="glyphicon glyphicon-print"></span> Imprimir <span class="caret"></span>
                      </button>
                      <ul class="dropdown-menu" role="menu">
                        <li>
                          <a target='blank' href="<?= $this->url('medicalHistory') . '/viewHcmedications/' . $history->cod_adm ?>">Medicamentos</a>
                        </li>
                        <li>
                              <a target='blank' href="<?= $this->url('medicalHistory') . '/viewHcexams/' . $history->cod_adm ?>">Exámenes</a>
                        </li>
                        <li>
                              <a target='blank' href="<?= $this->url('medicalHistory') . '/viewHcincapacities/' . $history->cod_adm ?>">Incapacidad</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                          <a target='blank' href="<?= $this->url('medicalHistory') . '/viewHchistory/' . $history->cod_adm ?>">Historia</a>
                        </li>
                        <li>
                          <a target='blank' href="<?= $this->url('medicalHistory') . '/viewHistory/' . $history->cod_adm ?>">Completa</a>
                        </li>
                      </ul>
                    </div>

                </td>
            </tr>
            <?php endforeach; ?>
        </table>
    <?php else: ?>
        <div class="panel panel-warning">
            <div class="panel-body">
            Aún no se han registrado historias
            </div>
        </div>
    <?php endif; ?>
    </div>


    <div id="view-control-histories">
    <?php if (count($controlHistory)): ?>
        <table class="table table-striped table-hover table-condensed" id="control-history-table">
            <tr>
                <th><a href="#" id="app-control-histories-check"><span class="glyphicon glyphicon-unchecked"></span></a></th>
                <th>ID</th>
                <th>Ingreso</th>
                <th>Nombre del paciente</th>
                <th>Documento</th>
                <th>Tipo de <br /> documento</th>
                <th>Folio</th>
                <th>Tipo de  <br /> evolución</th>
                <th>Acciones</th>
            </tr>
            <?php foreach ($controlHistory as $history) : ?>
            <tr
                <?php if (trim($history->est_adm) == ''): echo "class='success'"; endif; ?>
                <?php if (trim($history->est_adm) == 'A'): echo "class='danger'"; endif; ?>
            >
                <td><input type="checkbox" data-selection-id="<?= $history->num_doc_pac ?>" class="control-history"></td>
                <td><?= $this->escapeHtml($history->cod_adm); ?></td>
                <td><?= $this->escapeHtml($history->fecha_reg); ?></td>
                <td><a class='cell' href='<?= $this->url('medicalHistory', array('action'=>'viewHistory', 'id' => $history->cod_adm)) ?>'><?= $this->escapeHtml($history->nom_pac); ?></a></td>
                <td><?= $this->escapeHtml($history->num_doc_pac); ?></td>
                <td><?= $this->escapeHtml($history->nom_tip_doc); ?></td>
                <td><span class='label label-info'><?= $this->escapeHtml($history->num_fol); ?></span></td>
                <td><?php
                    switch ($history->tip_evo) {
                        case 1:
                            echo "CONTROL MEDICINA GENERAL";
                            break;
                        case 2:
                            echo "CONTROL MEDICINA ESPECIALIZADA";
                            break;
                        default:
                            echo "Indefinido";
                            break;
                    }
                ?></td>
                <td>
                    <a href="<?php echo $this->url('medicalHistory', array('action'=>'viewHistory', 'id' => $history->cod_adm)) ?>" class="btn btn-xs btn-primary" role="button" title="Ver"><span class="glyphicon glyphicon-briefcase"></span> Ver</a>

                    <div class="btn-group">
                      <button type="button" class="btn btn-info btn-xs dropdown-toggle" data-toggle="dropdown">
                        <span style="font-size: 14px" class="glyphicon glyphicon-print"></span> Imprimir <span class="caret"></span>
                      </button>
                      <ul class="dropdown-menu" role="menu">
                        <li>
                          <a target='blank' href="<?= $this->url('medicalHistory') . '/viewHcmedications/' . $history->cod_adm ?>">Medicamentos</a>
                        </li>
                        <li>
                              <a target='blank' href="<?= $this->url('medicalHistory') . '/viewHcexams/' . $history->cod_adm ?>">Exámenes</a>
                        </li>
                        <li>
                              <a target='blank' href="<?= $this->url('medicalHistory') . '/viewHcincapacities/' . $history->cod_adm ?>">Incapacidad</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                          <a target='blank' href="<?= $this->url('medicalHistory') . '/viewHchistory/' . $history->cod_adm ?>">Historia</a>
                        </li>
                        <li>
                          <a target='blank' href="<?= $this->url('medicalHistory') . '/viewHistory/' . $history->cod_adm ?>">Completa</a>
                        </li>
                      </ul>
                    </div>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
    <?php else: ?>
        <div class="panel panel-warning">
            <div class="panel-body">
            Aún no se han registrado historias
            </div>
        </div>
    <?php endif; ?>
    </div>

    <h4>Patologias</h4>

        <div id="view-control-histories">
    <?php if (count($patologia)): ?>
        <table class="table table-striped table-hover table-condensed" id="control-history-table">
            <tr>
                <th><a href="#" id="app-control-histories-check"><span class="glyphicon glyphicon-unchecked"></span></a></th>
                <th>ID</th>
                <th>Ingreso</th>
                <th>Nombre del paciente</th>
                <th>Documento</th>
                <th>Tipo de <br /> documento</th>
                <th>Folio.</th>

                <th>Acciones</th>
            </tr>
            <?php foreach ($patologia as $history) : ?>
            <tr
                <?php if (trim($history->est_adm) == ''): echo "class='success'"; endif; ?>
                <?php if (trim($history->est_adm) == 'A'): echo "class='danger'"; endif; ?>
            >
                <td><input type="checkbox" data-selection-id="<?= $history->num_doc_pac ?>" class="control-history"></td>
                <td><?= $this->escapeHtml($history->cod_adm); ?></td>
                <td><?= $this->escapeHtml($history->fecha_reg); ?></td>
                <td><a class='cell' href='<?= $this->url('medicalHistory', array('action'=>'viewHistory', 'id' => $history->cod_adm)) ?>'><?= $this->escapeHtml($history->nom_pac); ?></a></td>
                <td><?= $this->escapeHtml($history->num_doc_pac); ?></td>
                <td><?= $this->escapeHtml($history->nom_tip_doc); ?></td>
                <td><span class='label label-info'><?= $this->escapeHtml($history->num_fol); ?></span></td>

                <td>
                 <a class="btn btn-xs btn-<?= (is_null($history->id_salud)) ? 'danger' : 'default' ?>" data-id="DIALOG_RIA" data-action='show-dialog' data-url="<?= $this->basePath() ?>/admissions/add-ria/4" data-title="SOLICITUD DE SERVICIO DE SALUD" data-type="post" data-width="large" data-object="v= { type : 'patologia', cod_tip_his : 4, num_ing : <?=  $history->cod_adm ?> }"><span class="glyphicon glyphicon-edit"   ></span> RIA</a>

                    <a href="<?php echo $this->url('medicalHistory', array('action'=>'viewHistory', 'id' => $history->cod_adm, 'type' => '4')) ?>" class="btn btn-xs btn-primary" role="button" title="Ver"><span class="glyphicon glyphicon-briefcase"></span> Ver</a>

                    <div class="btn-group">
                      <button type="button" class="btn btn-info btn-xs dropdown-toggle" data-toggle="dropdown">
                        <span style="font-size: 14px" class="glyphicon glyphicon-print"></span> Imprimir <span class="caret"></span>
                      </button>
                      <ul class="dropdown-menu" role="menu">




                        <li>
                          <a target='blank' href="<?= $this->url('medicalHistory') . '/viewHchistory/' . $history->cod_adm ?>/4">Historia</a>
                        </li>
                        <li>
                          <a target='blank' href="<?= $this->url('medicalHistory') . '/viewHistory/' . $history->cod_adm ?>/4">Completa</a>
                        </li>
                      </ul>
                    </div>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
    <?php else: ?>
        <div class="panel panel-warning">
            <div class="panel-body">
            Aún no se han registrado historias
            </div>
        </div>
    <?php endif; ?>
    </div>


        <h4>Liquidos</h4>

        <div id="view-control-histories">
    <?php if (count($liquidos)): ?>
        <table class="table table-striped table-hover table-condensed" id="control-history-table">
            <tr>
                <th><a href="#" id="app-control-histories-check"><span class="glyphicon glyphicon-unchecked"></span></a></th>
                <th>ID</th>
                <th>Ingreso</th>
                <th>Nombre del paciente</th>
                <th>Documento</th>
                <th>Tipo de <br /> documento</th>
                <th>Folio.</th>

                <th>Acciones</th>
            </tr>
            <?php foreach ($liquidos as $history) : ?>
            <tr
                <?php if (trim($history->est_adm) == ''): echo "class='success'"; endif; ?>
                <?php if (trim($history->est_adm) == 'A'): echo "class='danger'"; endif; ?>
            >
                <td><input type="checkbox" data-selection-id="<?= $history->num_doc_pac ?>" class="control-history"></td>
                <td><?= $this->escapeHtml($history->cod_adm); ?></td>
                <td><?= $this->escapeHtml($history->fecha_reg); ?></td>
                <td><a class='cell' href='<?= $this->url('medicalHistory', array('action'=>'viewHistory', 'id' => $history->cod_adm)) ?>'><?= $this->escapeHtml($history->nom_pac); ?></a></td>
                <td><?= $this->escapeHtml($history->num_doc_pac); ?></td>
                <td><?= $this->escapeHtml($history->nom_tip_doc); ?></td>
                <td><span class='label label-info'><?= $this->escapeHtml($history->num_fol); ?></span></td>

                <td>
                 <a class="btn btn-xs btn-<?= (is_null($history->id_salud)) ? 'danger' : 'default' ?>" data-id="DIALOG_RIA"  data-action='show-dialog' data-url="<?= $this->basePath() ?>/admissions/add-ria/5" data-title="SOLICITUD DE SERVICIO DE SALUD" data-type="post" data-width="large" data-object="v= { type : 'liquidos' , cod_tip_his : 5, num_ing : <?=  $history->cod_adm ?>  }"><span class="glyphicon glyphicon-edit"   ></span> RIA</a>

                    <a href="<?php echo $this->url('medicalHistory', array('action'=>'viewHistory', 'id' => $history->cod_adm, 'type' => '5')) ?>" class="btn btn-xs btn-primary" role="button" title="Ver"><span class="glyphicon glyphicon-briefcase"></span> Ver</a>

                    <div class="btn-group">
                      <button type="button" class="btn btn-info btn-xs dropdown-toggle" data-toggle="dropdown">
                        <span style="font-size: 14px" class="glyphicon glyphicon-print"></span> Imprimir <span class="caret"></span>
                      </button>
                      <ul class="dropdown-menu" role="menu">




                        <li>
                          <a target='blank' href="<?= $this->url('medicalHistory') . '/viewHchistory/' . $history->cod_adm ?>/5">Historia</a>
                        </li>
                        <li>
                          <a target='blank' href="<?= $this->url('medicalHistory') . '/viewHistory/' . $history->cod_adm ?>/5">Completa</a>
                        </li>
                      </ul>
                    </div>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
    <?php else: ?>
        <div class="panel panel-warning">
            <div class="panel-body">
            Aún no se han registrado historias
            </div>
        </div>
    <?php endif; ?>
    </div>


          <h4>Citologia</h4>

        <div id="view-control-histories">
    <?php if (count($citologia)): ?>
        <table class="table table-striped table-hover table-condensed" id="control-history-table">
            <tr>
                <th><a href="#" id="app-control-histories-check"><span class="glyphicon glyphicon-unchecked"></span></a></th>
                <th>ID</th>
                <th>Ingreso</th>
                <th>Nombre del paciente</th>
                <th>Documento</th>
                <th>Tipo de <br /> documento</th>
                <th>Folio.</th>

                <th>Acciones</th>
            </tr>
            <?php foreach ($citologia as $history) : ?>
            <tr
                <?php if (trim($history->est_adm) == ''): echo "class='success'"; endif; ?>
                <?php if (trim($history->est_adm) == 'A'): echo "class='danger'"; endif; ?>
            >
                <td><input type="checkbox" data-selection-id="<?= $history->num_doc_pac ?>" class="control-history"></td>
                <td><?= $this->escapeHtml($history->cod_adm); ?></td>
                <td><?= $this->escapeHtml($history->fecha_reg); ?></td>
                <td><a class='cell' href='<?= $this->url('medicalHistory', array('action'=>'viewHistory', 'id' => $history->cod_adm)) ?>'><?= $this->escapeHtml($history->nom_pac); ?></a></td>
                <td><?= $this->escapeHtml($history->num_doc_pac); ?></td>
                <td><?= $this->escapeHtml($history->nom_tip_doc); ?></td>
                <td><span class='label label-info'><?= $this->escapeHtml($history->num_fol); ?></span></td>

                <td>
                 <a class="btn btn-xs btn-<?= (is_null($history->id_salud)) ? 'danger' : 'default' ?>" data-id="DIALOG_RIA"  data-action='show-dialog' data-url="<?= $this->basePath() ?>/admissions/add-ria/6" data-title="SOLICITUD DE SERVICIO DE SALUD" data-type="post" data-width="large" data-object="v= { type : 'citologia' , cod_tip_his : 6, num_ing : <?=  $history->cod_adm ?> }"><span class="glyphicon glyphicon-edit"   ></span> RIA</a>

                    <a href="<?php echo $this->url('medicalHistory', array('action'=>'viewHistory', 'id' => $history->cod_adm, 'type' => '6')) ?>" class="btn btn-xs btn-primary" role="button" title="Ver"><span class="glyphicon glyphicon-briefcase"></span> Ver</a>

                    <div class="btn-group">
                      <button type="button" class="btn btn-info btn-xs dropdown-toggle" data-toggle="dropdown">
                        <span style="font-size: 14px" class="glyphicon glyphicon-print"></span> Imprimir <span class="caret"></span>
                      </button>
                      <ul class="dropdown-menu" role="menu">




                        <li>
                          <a target='blank' href="<?= $this->url('medicalHistory') . '/viewHchistory/' . $history->cod_adm ?>/6">Historia</a>
                        </li>
                        <li>
                          <a target='blank' href="<?= $this->url('medicalHistory') . '/viewHistory/' . $history->cod_adm ?>/6">Completa</a>
                        </li>
                      </ul>
                    </div>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
    <?php else: ?>
        <div class="panel panel-warning">
            <div class="panel-body">
            Aún no se han registrado historias
            </div>
        </div>
    <?php endif; ?>
    </div>

<?php endif; ?>