<?php if (isset($Exception)): ?>

	<div class="alert alert-danger alert-dismissable">
	  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> <?= $Exception ?>
	</div>

<?php else: ?>

	<div class="alert alert-success">
		<strong><i class="fa fa-ok"></i></strong> Preview <br />

		<?php if ($type == '1'): ?>

			<?php foreach ($files as $file): ?>

				<audio controls preload="none" style="width:480px;">
					<source src="<? $this->basePath() ?>/cache/temp_dir/<?= $file ?>" type="audio/mp4" />
					<source src="<? $this->basePath() ?>/cache/temp_dir/<?= $file ?>" type="audio/ogg" />
					<p>Your browser does not support HTML5 audio.</p>
				</audio>

			<?php endforeach; ?>

		<?php elseif ($type == '2'): ?>

			<?php foreach ($files as $file): ?>
				<img src="<? $this->basePath() ?>/cache/temp_dir/<?= $file ?>" alt="<?= $file ?>" width="100" />
			<?php endforeach; ?>

		<?php endif; ?>
	</div>

<?php endif; ?>