<?php if (!$xmlHttpRequest || !$simulateXmlHttpRequest): ?>
    <div id="setting-controls">
        <p>
        <div class="btn-group">
          <button type="button" class="btn btn-default" id="run-certification-refresh" title="actualizar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'view-certifications', 'id' => $admission->cod_adm)) ?>"><span class="glyphicon glyphicon-refresh"></span></button>
          <button type="button" class="btn btn-default" id="edit-selected-certifications" title="editar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'edit-certification', 'id' => $admission->cod_adm)) ?>"><span class="glyphicon glyphicon-pencil"></span></button>
          <button type="button" class="btn btn-default" id="delete-selected-certifications" title="eliminar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'delete-certifications', 'id' => $admission->cod_adm)) ?>"><span class="glyphicon glyphicon-trash"></span></button>
        </div>
        </p>
    </div>
<?php endif; ?>

<div id="view-certifications">
<?php if (count($certifications)): ?>
    <table class="table table-striped table-hover table-condensed" id="certifications-table">
        <tr>
            <th><input id="app-certifications-check" type="checkbox" /></th>
            <th>Fecha</th>
            <th>Título</th>
            <th>Detalle</th>
        </tr>   
        <?php foreach ($certifications as $certification) : ?>
        <tr>
            <td><input type="checkbox" data-selection-id="<?= $certification->cod_cer ?>" class="certification"></td>
            <td><?= $this->escapeHtml($certification->fec_reg); ?> </td>
            <td><?php $obs = trim($certification->tit_cer); if (empty($obs)) echo "Sín título"; else echo $this->escapeHtml($obs) ?></td>       
            <td><?php $obs = trim($certification->des_cer); if (empty($obs)) echo "Ninguna"; else echo $this->escapeHtml($obs) ?></td>
        </tr>
        <?php endforeach; ?>
    </table>
<?php else: ?>
    <div class="panel panel-warning">
        <div class="panel-body">
        Aún no se han registrado certificaciones
        </div>
    </div>
<?php endif; ?>
</div>