<h4>Folios del paciente</h4>

<div id="view-folios">
<?php if (count($folios)): ?>
    <table class="table table-striped table-hover table-condensed" id="folios-table">
        <tr>
            <th>Folio</th>
            <th>Registro</th>
            <th>Tipo de historia</th>
            <th>Médico</th>
            <th>Acciones</th>
        </tr>
        <?php foreach ($folios as $folio) : ?>
        <tr <?php if ($folio->admission == $admission->cod_adm && $folio->tipohis == $type) echo "class='success'" ?> >
            <td><?= $this->escapeHtml($folio->folio); ?> </td>
            <td><?= $this->escapeHtml($folio->registro); ?> </td>
            <td><?= $typeHistory[$folio->tipohis] ?></td>
            <td><?= $this->escapeHtml($folio->medico); ?> </td>
            <td>
                <a href="<?php echo $this->url('medicalHistory',
                array('action'=>'viewHistory', 'id' => $folio->admission, 'type' => $folio->tipohis));?>"
                class="btn btn-link" title="Ver"><span class="glyphicon <?= ($folio->admission == $admission->cod_adm && $folio->tipohis == $type) ? 'glyphicon-check' : 'glyphicon glyphicon-unchecked' ?>"></span> Ver</a>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
<?php else: ?>
    <div class="panel panel-warning">
        <div class="panel-body">
        Aún no se han registrado folios para el paciente
        </div>
    </div>
<?php endif; ?>
</div>
