<?php if (!$xmlHttpRequest): ?>

<a class="back-button" href="<?php echo $this->url('medicalHistory', array('action'=>'viewHistory', 'id' => $admission->cod_adm)); ?>">
  <span class="glyphicon glyphicon-circle-arrow-left" style="font-size: 50px; color: rgb(0,150,200)" title="Historia del paciente"></span>
</a>

<img src="<?php echo $this->basePath('img/logo_medicadiz_min.png') ?>" alt="Logo medicadiz" width="150" style="display: none; position: absolute" class="logo-empresa" />

<div class="container print-header" style="text-align: center; display: none">
    <h3>NOMBRE DE LA CLÍNICA</h3>
    <h4>SOLICITUD DE INTERCONSULTA</h4><br /><br />
</div>

    <?php if (!is_null($interconsultation)): ?>
        <div class="panel panel-default">
            <div class="panel-heading">Datos generales</div>
            <div class="panel-body">
                <table class="table table-no-bordered no-margin table-no-padding">
                    <tbody>
                        <tr>
                            <td><strong>No. Ingreso:</strong> <?= $admission->cod_adm ?></td>
                            <td><strong>Fecha Ingreso:</strong> <?= $admission->fec_adm ?></td>
                            <td><strong>Fecha de expedición:</strong> <?= date("Y-m-d") ?></td>
                        </tr>
                        <tr>
                            <td><strong>Entidad:</strong> <?= $admission->nom_ent ?></td>
                            <td colspan="2"><strong>Folio:</strong> <?= $admission->num_fol ?></td>
                        </tr>
                    </tbody>
                </table>    
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">Datos personales</div>
            <div class="panel-body">
                <table class="table table-no-bordered no-margin table-no-padding">
                    <tbody>
                        <tr>
                            <td><strong>Paciente:</strong> <?= $admission->nom_pac ?></td>
                            <td><strong>Identificación:</strong> <?= $admission->num_doc_pac ?></td>
                            <td><strong>Fecha de nacimiento:</strong> <?= $admission->fec_nac_pac ?></td>
                        </tr>
                        <tr>
                            <td><strong>Dirección:</strong> <?= $admission->dir_pac ?></td>
                            <td colspan="2"><strong>Teléfono:</strong> <?= (!empty($admission->num_tel_pac)) ? $admission->num_tel_pac : " --- " ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div>
                <strong>Motivo de la interconsulta: </strong> <?= $this->escapeHtml($interconsultation->mot_int); ?><br /><br />
                <strong>Diagnóstico:</strong> <?= $this->escapeHtml($interconsultation->cod_dia)." - ".$this->escapeHtml($interconsultation->nom_dia); ?><br /><br />
                <strong>Especialidad:</strong> <?= $this->escapeHtml($interconsultation->cod_esp)." - ".$this->escapeHtml($interconsultation->nom_esp); ?>
        </div><br />        

    <?php endif; ?>

<?php else: ?>

    <h4 style="text-align: center">Interconsultas</h4>

    <div id="view-diagnostics">
    <?php if (count($interconsultations)): ?>
        <table class="table table-striped table-hover table-condensed" id="folios-table">
            <tr>
                <th>Id Esp.</th>
                <th>Especialidad</th>
                <th>Id Diag.</th>
                <th>Diagnóstico</th>
                <th>Motivo</th>
                <th>Acción</th>
            </tr>   
            <?php foreach ($interconsultations as $interconsultation) : ?>
            <tr>
                <td><?= $this->escapeHtml($interconsultation->cod_esp); ?> </td>
                <td><?= $this->escapeHtml($interconsultation->nom_esp); ?> </td>
                <td><?= $this->escapeHtml($interconsultation->cod_dia); ?> </td>
                <td><?= $this->escapeHtml($interconsultation->nom_dia); ?> </td>
                <td><?php $obs = trim($interconsultation->mot_int); if (empty($obs)) echo "Ninguna"; else echo $this->escapeHtml($obs) ?></td>
                <td>
                <a title="Ver diseño de impresión" href="<?php echo $this->url('medicalHistory', array('action'=>'viewHcinterconsultations', 'id' => $admission->cod_adm, 'type' => $interconsultation->cod_int)); ?>"><span style="font-size: 20px" class="glyphicon glyphicon-search"></span> Visualizar</a>                
                </td>                
            </tr>
            <?php endforeach; ?>
        </table>
    <?php else: ?>
        <div class="panel panel-warning">
            <div class="panel-body">
            No se registraron interconsultas en el folio
            </div>
        </div>
    <?php endif; ?>
    </div>
<?php endif; ?>

<?php if (!$xmlHttpRequest): ?>
<div class="container" style="text-align: center">
Médico: <em><?= $admission->usu_med ?></em>
</div>
<br /><br />
<button class="btn btn-default print-function" title="Imprimir"><span style="font-size: 20px" class="glyphicon glyphicon-print"></span> Imprimir</button>
<button class="btn btn-default view-print-version" title="Diseño de impresión"><span style="font-size: 20px" class="glyphicon glyphicon-search"></span></button>
<?php endif; ?>