<?php if (!$xmlHttpRequest || !$simulateXmlHttpRequest): ?>
    <div id="setting-controls">
        <p>
        <div class="btn-group">
          <button type="button" class="btn btn-default" id="run-background-refresh" title="actualizar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'view-backgrounds', 'id' => $admission->cod_adm)) ?>"><span class="glyphicon glyphicon-refresh"></span></button>
          <button type="button" class="btn btn-default" id="edit-selected-backgrounds" title="editar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'edit-background', 'id' => $admission->cod_adm)) ?>"><span class="glyphicon glyphicon-pencil"></span></button>
          <button type="button" class="btn btn-default" id="delete-selected-backgrounds" title="eliminar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'delete-backgrounds', 'id' => $admission->cod_adm)) ?>"><span class="glyphicon glyphicon-trash"></span></button>
        </div>
        </p>
    </div>
<?php endif; ?>

<div id="view-backgrounds">
<?php if (count($backgrounds)): ?>
    <table class="table table-striped table-hover table-condensed" id="backgrounds-table">
        <tr>
            <th><input id="app-backgrounds-check" type="checkbox" /></th>
            <th>Fecha</th>
            <th>Tipo</th>
            <th>Detalle</th>
        </tr>   
        <?php foreach ($backgrounds as $background) : ?>
        <tr>
            <td><input type="checkbox" data-selection-id="<?= $background->cod_ant ?>" class="background"></td>
            <td><?= $this->escapeHtml($background->fec_reg); ?> </td>
            <td><?php
            switch ($background->tip_ant) {
                case 1:
                    echo "Médicos";
                    break;
                case 2:
                    echo "Quirúrgicos";
                    break;
                case 3:
                    echo "Transfusionables";
                    break;
                case 4:
                    echo "Tóxicos";
                    break;
                case 5:
                    echo "Inmunológicos";
                    break;
                case 6:
                    echo "Alérgicos";
                    break;
                case 7:
                    echo "Traumáticos";
                    break;
                case 8:
                    echo "Psiquiátricos";
                    break;
                case 9:
                    echo "Ginecológicos";
                    break;
                case 10:
                    echo "Farmacológicos";
                    break;
                case 11:
                    echo "Familiares";
                    break;
                case 12:
                    echo "Psicológicos";
                    break;
                case 13:
                    echo "Otros";
                    break;
                default:
                    echo "Indefinido";
                    break;
            }
            ?></td>              <td><?php $obs = trim($background->des_ant); if (empty($obs)) echo "Ninguna"; else echo $this->escapeHtml($obs) ?></td>
        </tr>
        <?php endforeach; ?>
    </table>
<?php else: ?>
    <div class="panel panel-warning">
        <div class="panel-body">
        Aún no se han registrado antecedentes
        </div>
    </div>
<?php endif; ?>
</div>