<?php if (!$xmlHttpRequest || !$simulateXmlHttpRequest): ?>
    <div id="setting-controls">
        <p>
        <div class="btn-group">
          <button type="button" class="btn btn-default" id="run-interconsultations-refresh" title="actualizar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'view-interconsultations', 'id' => $admission->cod_adm)) ?>"><span class="glyphicon glyphicon-refresh"></span></button>
          <button type="button" class="btn btn-default" id="edit-selected-interconsultations" title="editar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'edit-interconsultation', 'id' => $admission->cod_adm)) ?>"><span class="glyphicon glyphicon-pencil"></span></button>
          <button type="button" class="btn btn-default" id="delete-selected-interconsultations" title="eliminar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'delete-interconsultations', 'id' => $admission->cod_adm)) ?>"><span class="glyphicon glyphicon-trash"></span></button>
        </div>
        </p>
    </div>
<?php endif; ?>

<div id="view-interconsultations">
<?php if (count($interconsultations)): ?>
    <table class="table table-striped table-hover table-condensed" id="interconsultations-table">
        <tr>
            <th><input id="app-interconsultations-check" type="checkbox" /></th>
            <th>Diagnóstico</th>
            <th>Especialidad</th>
            <th>Motivo</th>
        </tr>
        <?php foreach ($interconsultations as $interconsultation) : ?>
        <tr>
            <td><input type="checkbox" data-selection-id="<?= $interconsultation->cod_int ?>" class="interconsultation"></td>
            <td><?= $this->escapeHtml($interconsultation->nom_dia); ?> </td>
            <td><?= $this->escapeHtml($interconsultation->nom_esp); ?></td>
            <td><?php $obs = trim($interconsultation->mot_int); if (empty($obs)) echo "Ninguno"; else echo $this->escapeHtml($obs) ?></td>
        </tr>
        <?php endforeach; ?>
    </table>
<?php else: ?>
    <div class="panel panel-warning">
        <div class="panel-body">
        Aún no se han registrado interconsultas
        </div>
    </div>
<?php endif; ?>
</div>