<?php if (!$xmlHttpRequest || !$simulateXmlHttpRequest): ?>
    <div id="setting-controls">
        <p>
        <div class="btn-group">
          <button type="button" class="btn btn-default" id="run-incapacities-refresh" title="actualizar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'view-incapacities', 'id' => $admission->cod_adm)) ?>"><span class="glyphicon glyphicon-refresh"></span></button>
          <button type="button" class="btn btn-default" id="edit-selected-incapacities" title="editar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'edit-incapacity', 'id' => $admission->cod_adm)) ?>"><span class="glyphicon glyphicon-pencil"></span></button>
          <button type="button" class="btn btn-default" id="delete-selected-incapacities" title="eliminar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'delete-incapacities', 'id' => $admission->cod_adm)) ?>"><span class="glyphicon glyphicon-trash"></span></button>
        </div>

        <div class="btn-group">
          <button type="button" class="btn btn-default" id="incapacities-alternation-table" title="alternar vista" data-exception="[1]"><span class= "glyphicon glyphicon-list-alt"></span></button>
        </div>
        </p>
    </div>
<?php endif; ?>

<div id="view-incapacities">
<?php if (count($incapacities)): ?>
    <table class="table table-striped table-hover table-condensed" id="incapacities-table">
        <tr>
            <th><input id="app-incapacities-check" type="checkbox" /></th>
            <th style="display: none">Código</th>
            <th>Diagnóstico</th>
            <th>Fecha de inicio</th>
            <th>Número de días</th>
            <th style="display: none">Descripción</th>
        </tr>   
        <?php foreach ($incapacities as $incapacity) : ?>
        <tr>
            <td><input type="checkbox" data-selection-id="<?= $incapacity->cod_dia ?>" class="incapacity"></td>
            <td style="display: none"><?= $this->escapeHtml($incapacity->cod_dia); ?> </td>           
            <td><?= $this->escapeHtml($incapacity->nom_dia); ?> </td>           
            <td><?= $this->escapeHtml($incapacity->fec_ini_inc); ?></td>
            <td><?= $this->escapeHtml($incapacity->num_dia_inc); ?></td>
            <td style="display: none"><?php $obs = trim($incapacity->des_inc); if (empty($obs)) echo "Ninguna"; else echo $this->escapeHtml($obs) ?></td>
        </tr>
        <?php endforeach; ?>
    </table>
<?php else: ?>
    <div class="panel panel-warning">
        <div class="panel-body">
        Aún no se ha registrado una incapacidad
        </div>
    </div>
<?php endif; ?>
</div>