<?php
    switch ($type) {
        case 1:
            $_type = "exam";
            break;
        case 2:
            $_type = "pathology";
            break;        
        case 3:
            $_type = "proc-qx";
            break;
        case 4:
            $_type = "proc";
            break;
    }
?>


<?php if (!$xmlHttpRequest || !$simulateXmlHttpRequest): ?>
    <div id="setting-controls">
        <p>
        <div class="btn-group">
          <button type="button" class="btn btn-default" id="run-<?= $_type ?>-solicitude-refresh" title="actualizar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'view-solicitudes', 'id' => $admission->cod_adm, 'type' => $type)) ?>"><span class="glyphicon glyphicon-refresh"></span></button>
          <button type="button" class="btn btn-default" id="edit-selected-<?= $_type ?>-solicitudes" title="editar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'edit-solicitude', 'id' => $admission->cod_adm, 'type' => $type)) ?>"><span class="glyphicon glyphicon-pencil"></span></button>
          <button type="button" class="btn btn-default" id="delete-selected-<?= $_type ?>-solicitudes" title="eliminar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'delete-solicitudes', 'id' => $admission->cod_adm, 'type' => $type)) ?>"><span class="glyphicon glyphicon-trash"></span></button>
        </div>
        </p>
    </div>
<?php endif; ?>

<div id="view-<?= $_type ?>-solicitudes">
<?php if (count($solicitudes)): ?>
    <table class="table table-striped table-hover table-condensed" id="<?= $_type ?>-solicitudes-table">
        <tr>
            <th><input id="app-<?= $_type ?>-solicitudes-check" type="checkbox" /></th>
            <th>Nombre</th>
            <th>Cantidad</th>
            <th>Estado</th>
            <th>Observación</th>
        </tr>   
        <?php foreach ($solicitudes as $solicitude) : ?>
        <tr>
            <td><input type="checkbox" data-selection-id="<?= $solicitude->cod_exa ?>" class="<?= $_type ?>-solicitude"></td>
            <td><?= $this->escapeHtml($solicitude->nom_exa); ?></td>
            <td><?= $this->escapeHtml($solicitude->can_exa); ?></td>
            <td><?php  
                switch ($solicitude->est_exa) {
                    case 1:
                        echo "Rutinaria";
                        break;
                    case 2:
                        echo "Urgente";
                        break;                    
                    default:
                        echo "Indefinida";
                        break;
                }
            ?></td>
            <td><?php $obs = trim($solicitude->obs_exa); if (empty($obs)) echo "Ninguna"; else echo $this->escapeHtml($obs) ?></td>
        </tr>
        <?php endforeach; ?>
    </table>
<?php else: ?>
    <div class="panel panel-warning">
        <div class="panel-body">
        Aún no se han registrado exámenes
        </div>
    </div>
<?php endif; ?>
</div>