<?php if (isset($Exception)): ?>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> <?= $Exception ?>
</div>
<?php endif; ?>

<?php if (!isset($Exception)): ?>
  <?php
  $title = 'Historia Clínica';
  $this->headTitle($title);
  ?>

  <a href="<?php echo $this->url('medicalHistory', array('action'=>'admission', 'id' => $admission->cod_adm, 'type' => $type)); ?>">
    <span class="glyphicon glyphicon-circle-arrow-left" style="font-size: 50px; color: rgb(0,150,200)" title="Admisión"></span>
  </a>

  <a href="<?php echo $this->url('medicalHistory', array('action'=>'index')); ?>">
    <span class="glyphicon glyphicon-dashboard" style="font-size: 50px; color: rgb(0,150,200)" title="Historia médica"></span>
  </a>

  <?php if (count($admission)): ?>
  <div style="display: inline-block; margin-left: 50px">
    <strong>ID admisión:</strong> <?= $admission->cod_adm ?> <br />
    <strong>Paciente:</strong> <?= $admission->nom_pac ?> <br />
    <strong>Médico:</strong> <?= $admission->usu_med ?> <br />
  </div>
  <?php endif; ?>

  <h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="thumbnail" style="margin-top: 15px">
  <button class="btn btn-default" id="add-certification" data-resource="<?= $this->url('medicalHistory') . '/addCertification/' . $admission->cod_adm ?>"><span class="glyphicon glyphicon-file"></span> Certificaciones</button>
  <button class="btn btn-default" id="add-background" data-resource="<?= $this->url('medicalHistory') . '/add-Background/' . $admission->cod_adm ?>"><span class="glyphicon glyphicon-file"></span> Antecedentes</button>
</div><br />

<div class="plts-layout simple-grid">
<div class="left-sidebar" style="text-align: center; margin-right: 10px">
    <span class="glyphicon glyphicon-briefcase" style="display: block; font-size: 6em"></span><br />
  <div class="btn-group-vertical" style="width: 100%">
    <button class="btn btn-default" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'view-hcfolios', 'id' => $admission->cod_adm, 'type' => $type));?>" id="hc-folios-mode">Folios</button>
    <button class="btn btn-default btn" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'view-hcobservations', 'id' => $admission->cod_adm, 'type' => $type));?>" id="hc-certifications-mode">Observaciones</button>

    <br /><h4>Registro</h4><hr />

    <button class="btn btn-default btn" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'view-hcdiagnostics', 'id' => $admission->cod_adm, 'type' => $type));?>" id="hc-diagnostics-mode">Diagnósticos</button>
    <button class="btn btn-default btn" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'view-hcmedications', 'id' => $admission->cod_adm, 'type' => $type));?>" id="hc-medications-mode">Medicamentos</button>
    <button class="btn btn-default btn" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'view-hcexams', 'id' => $admission->cod_adm, 'type' => $type));?>" id="hc-exams-mode">Exámenes</button>
    <button class="btn btn-default btn" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'view-hcinterconsultations', 'id' => $admission->cod_adm, 'type' => $type));?>" id="hc-interconsultations-mode">Interconsultas</button>
    <button class="btn btn-default btn" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'view-hcincapacities', 'id' => $admission->cod_adm, 'type' => $type));?>" id="hc-incapacities-mode">Incapacidad</button>
    <button class="btn btn-default btn" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'view-hccertifications', 'id' => $admission->cod_adm, 'type' => $type));?>" id="hc-certifications-mode">Certificaciones</button>

    <br /><h4>Informes</h4><hr />

    <button class="btn btn-default btn" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'view-hchistory', 'id' => $admission->cod_adm, 'type' => $type));?>" id="hc-diagnostics-mode">Historia Clínica</button>
  </div>
</div>
  <div id="view-hchistory" class="contents">

    <h4>Folios del paciente</h4>
      <div id="view-folios">
      <?php if (count($folios)): ?>
          <table class="table table-striped table-hover table-condensed" id="folios-table">
              <tr>
                  <th>Folio</th>
                  <th>Registro</th>
                  <th>Tipo de historia</th>
                  <th>Médico</th>
                  <th>Acciones</th>
              </tr>
              <?php foreach ($folios as $folio) : ?>
              <tr <?php if ($folio->admission == $admission->cod_adm && $folio->tipohis == $type) echo "class='success'" ?> >
                  <td><?= $this->escapeHtml($folio->folio); ?> </td>
                  <td><?= $this->escapeHtml($folio->registro); ?> </td>
                  <td><?= $typeHistory[$folio->tipohis] ?></td>
                  <td><?= $this->escapeHtml($folio->medico); ?> </td>
                  <td>
                     <a href="<?php echo $this->url('medicalHistory',
                     array('action'=>'viewHistory', 'id' => $folio->admission, 'type' => $folio->tipohis));?>"
                     class="btn btn-link" title="Ver"><span class="glyphicon <?= ($folio->admission == $admission->cod_adm && $folio->tipohis == $type) ? 'glyphicon-check' : 'glyphicon glyphicon-unchecked' ?>"></span> Ver</a>
                  </td>
              </tr>
              <?php endforeach; ?>
          </table>
      <?php else: ?>
          <div class="panel panel-warning">
              <div class="panel-body">
              Aún no se han registrado folios para el paciente
              </div>
          </div>
      <?php endif; ?>
      </div>
  </div>
</div>
<?php endif; ?>