<?php if (!$xmlHttpRequest || !$simulateXmlHttpRequest): ?>
    <div id="setting-controls">
        <p>
        <div class="btn-group">
          <button type="button" class="btn btn-default" id="run-indication-refresh" title="actualizar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'view-medications', 'id' => $admission->cod_adm)) ?>"><span class="glyphicon glyphicon-refresh"></span></button>
          <button type="button" class="btn btn-default" id="edit-selected-indications" title="editar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'edit-medication', 'id' => $admission->cod_adm)) ?>"><span class="glyphicon glyphicon-pencil"></span></button>
          <button type="button" class="btn btn-default" id="delete-selected-indications" title="eliminar" data-resource="<?php echo $this->url('medicalHistory', array('action'=>'delete-medications', 'id' => $admission->cod_adm)) ?>"><span class="glyphicon glyphicon-trash"></span></button>
        </div>
        </p>
    </div>
<?php endif; ?>

<div id="view-indications">
<?php if (count($indications)): ?>
    <table class="table table-striped table-hover table-condensed" id="indications-table">
        <tr>
            <th><input id="app-indications-check" type="checkbox" /></th>
            <th>Código</th>
            <th>Detalle de la indicación</th>
        </tr>
        <?php foreach ($indications as $indication) : ?>
        <tr>
            <td><input type="checkbox" data-selection-id="<?= $indication->cod_ind ?>" class="indication"></td>
            <td><?= $this->escapeHtml($indication->cod_ind); ?> </td>
            <td><?php $obs = trim($indication->indicacion); if (empty($obs)) echo "Ninguna"; else echo $this->escapeHtml($obs) ?></td>
        </tr>
        <?php endforeach; ?>
    </table>
<?php else: ?>
    <div class="panel panel-warning">
        <div class="panel-body">
        Aún no se han registrado indicaciones
        </div>
    </div>
<?php endif; ?>
</div>