<?php if (!$identity): ?>
<div class="$ black-shadow slow jumbotron well enlighten">
    <h1 class="$ slide-left-in">
        ServiClinical
    </h1>
    <p class="$ slide-right-in">
        Toda la tecnología a tu alcance
    </p>
    <p class="$ fade-in infinite slow">
        <img src="<?= $this->basePath("img/logo.png") ?>" alt="logo" class="$ fade-out infinite slow" />        
    </p>
    <p>
        <a href="<?= $this->url('auth', array('action' => 'login')) ?>" class="$ slide-left-in btn btn-warning btn-large" href="#"><span class="glyphicon glyphicon-user"></span> Iniciar sesión</a>
    </p>
</div>
<?php else: ?>
<div class="container">
    <div class="row clearfix">
        <div class="col-md-4 column">
            <?php if (isset($acl) && ($acl->isAllowed("viewUsers") || $acl->isAllowed("viewPermissions"))): ?>
                <a style="text-decoration: none" class="thumbnail" href="<?= $this->url('auth', array('action' => 'index')) ?>" title="Usuarios"><span class="glyphicon glyphicon-user" style="font-size: 100px"></span> <span style="font-size: 30px">Usuarios</span></a>
            <?php endif; ?>
                <a style="text-decoration: none" class="thumbnail" href="<?= $this->url('auth', array('action' => 'me')) ?>" title="Mi perfil"><span class="glyphicon glyphicon-pencil" style="font-size: 100px"></span> <span style="font-size: 30px">Mi perfil</span></a>
        </div>
        <div class="col-md-4 column">
            <?php if (isset($acl) && ($acl->isAllowed("viewAdmissions") || $acl->isAllowed("viewPatients"))): ?>
                <a style="text-decoration: none" class="thumbnail" href="<?= $this->url('admissions', array('action' => 'index')) ?>" title="Admisiones"><span class="glyphicon glyphicon-ok" style="font-size: 100px"></span> <span style="font-size: 28px">Admisiones</span></a>
            <?php endif; ?>
            <?php if (isset($acl) && $acl->isAllowed("viewHistory")): ?>
                <a style="text-decoration: none" class="thumbnail" href="<?= $this->url('medicalHistory', array('action' => 'index')) ?>" title="Historia clínica"><span class="glyphicon glyphicon-time" style="font-size: 100px"></span> <span style="font-size: 22px">Historia clínica</span></a>
            <?php endif; ?>
        </div>
        <div class="col-md-4 column">
            <?php if (isset($acl) && ($acl->isAllowed("viewExams") || $acl->isAllowed("viewMedications") || $acl->isAllowed("entities"))): ?>
                <a style="text-decoration: none" class="thumbnail" href="<?= $this->url('settings', array('action' => 'index')) ?>" title="Configuración"><span class="glyphicon glyphicon-cog" style="font-size: 100px"></span> <span style="font-size: 23px">Configuración</span></a>
            <?php endif; ?>
            <?php if (isset($acl) && $acl->isAllowed("viewDevelopment")): ?>            
                <a style="text-decoration: none" class="thumbnail" href="<?= $this->url('application', array('action' => 'development')) ?>" title="Desarrollo"><span class="glyphicon glyphicon-tags" style="font-size: 100px"></span> <span style="font-size: 28px">&nbsp;Desarrollo</span></a>
            <?php endif; ?>
        </div>
    </div>
</div>
<?php endif; ?>

<div class="$ slide-right-in row clearfix" style="margin-top: 20px">
    <div class="col-md-6 column">
        <p>
            Serviclinical - Historia clínica y facturación
        </p>
    </div>
    <div class="col-md-6 column">
        <p>
        Copyright <strong>(c)</strong> 2017 Pleets
        </p>
    </div>
</div>